<?php
return array (
  451 => 
  array (
    'id' => '451',
    'content' => '植发后多久看不出痕迹？<br />
',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'relation' => '',
    'voteid' => '0',
    'allow_comment' => '1',
    'copyfrom' => '|0',
    'catid' => '94',
    'typeid' => '0',
    'title' => '植发后多久看不出痕迹？',
    'style' => '',
    'thumb' => '',
    'keywords' => '植发 痕迹',
    'description' => '植发后多久看不出痕迹？',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/fyywjd/0309_451.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1425887943',
    'updatetime' => '1425887951',
  ),
  450 => 
  array (
    'id' => '450',
    'content' => '植发后还会脱落吗？<br />
',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'relation' => '',
    'voteid' => '0',
    'allow_comment' => '1',
    'copyfrom' => '|0',
    'catid' => '94',
    'typeid' => '0',
    'title' => '植发后还会脱落吗？',
    'style' => '',
    'thumb' => '',
    'keywords' => '植发',
    'description' => '植发后还会脱落吗？',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/fyywjd/0309_450.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1425887929',
    'updatetime' => '1425887938',
  ),
  449 => 
  array (
    'id' => '449',
    'content' => '植发有副作用吗？<br />
',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'relation' => '',
    'voteid' => '0',
    'allow_comment' => '1',
    'copyfrom' => '|0',
    'catid' => '94',
    'typeid' => '0',
    'title' => '植发有副作用吗？',
    'style' => '',
    'thumb' => '',
    'keywords' => '植发 副作用',
    'description' => '植发有副作用吗？',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/fyywjd/0309_449.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1425887917',
    'updatetime' => '1425887923',
  ),
  448 => 
  array (
    'id' => '448',
    'content' => '植发需要多少钱？<br />
',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'relation' => '',
    'voteid' => '0',
    'allow_comment' => '1',
    'copyfrom' => '|0',
    'catid' => '94',
    'typeid' => '0',
    'title' => '植发需要多少钱？',
    'style' => '',
    'thumb' => '',
    'keywords' => '植发',
    'description' => '植发需要多少钱？',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/fyywjd/0309_448.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1425887888',
    'updatetime' => '1425887911',
  ),
);
?>