<?php
return array (
  422 => 
  array (
    'id' => '422',
    'catid' => '95',
    'typeid' => '0',
    'title' => '5月雍禾植发推出5大保障协议',
    'style' => '',
    'thumb' => '',
    'keywords' => '雍禾植发',
    'description' => '2014年5月11日下午，北京雍禾植发在兆龙饭店举行大型发友会，本次会议内容丰富，但就新闻点来说，雍禾推出的五大保障协议更能吸引人的眼球   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zfbzxy/0305_422.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1425532484',
    'updatetime' => '1425532524',
  ),
  423 => 
  array (
    'id' => '423',
    'catid' => '95',
    'typeid' => '0',
    'title' => '关于不过度医疗和推销药物保障',
    'style' => '',
    'thumb' => '',
    'keywords' => '药物 医疗',
    'description' => '1 现在不少医院存在过度医疗的问题，甚至在某些医院有愈演愈烈之势，中国植发业是不是也存在此问题?过度医疗一直为广大患者所诟病，因为它   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zfbzxy/0305_423.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1425533165',
    'updatetime' => '1425533214',
  ),
  424 => 
  array (
    'id' => '424',
    'catid' => '95',
    'typeid' => '0',
    'title' => '关于毛囊成活率保障的相关问题',
    'style' => '',
    'thumb' => '',
    'keywords' => '成活率 毛囊 问题',
    'description' => '1 雍禾植发的毛囊成活率是一个怎么样的百分比保障?雍禾植发的毛囊成活率确保95%，也就是说我们为你种植100毛囊单位，确保成活95个毛囊单位   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zfbzxy/0305_424.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1425533224',
    'updatetime' => '1425533255',
  ),
  425 => 
  array (
    'id' => '425',
    'catid' => '95',
    'typeid' => '0',
    'title' => '关于医生亲诊相关问题',
    'style' => '',
    'thumb' => '',
    'keywords' => '医生 问题',
    'description' => '1 什么是植发手术中的医生亲诊?植发手术的医生亲诊，并不是雍禾的手术全由医生包揽，而是医生该做的环节必须是医生做，护士绝对是不能代劳   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zfbzxy/0305_425.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1425533307',
    'updatetime' => '1425533344',
  ),
  426 => 
  array (
    'id' => '426',
    'catid' => '95',
    'typeid' => '0',
    'title' => '关于预约金保障的相关问题',
    'style' => '',
    'thumb' => '',
    'keywords' => '问题',
    'description' => '1 雍禾的植发手术必须要缴预约金吗?不一定的。如果你今天来雍禾植发咨询手术，并且当天做植发手术，这是不需要预约金的。而所谓的预约金指   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zfbzxy/0305_426.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1425533386',
    'updatetime' => '1425533431',
  ),
  427 => 
  array (
    'id' => '427',
    'catid' => '95',
    'typeid' => '0',
    'title' => '雍禾植发郑重承诺',
    'style' => '',
    'thumb' => '',
    'keywords' => '禾植发',
    'description' => '因为品质卓越，所以敢于透明，雍禾植发郑重承诺：将透明医疗，签约植发这一理念贯穿每一台植发手术的始终，并长期服务每一位发友！全国联保   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zfbzxy/0305_427.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1425533444',
    'updatetime' => '1425533467',
  ),
);
?>