<?php
return array (
  198 => 
  array (
    'id' => '198',
    'catid' => '51',
    'typeid' => '0',
    'title' => '专家全面解析植发价格中的陷阱',
    'style' => '',
    'thumb' => '',
    'keywords' => '陷阱 专家 价格',
    'description' => '导读：其实在我们生活中经常会被商家给出的价格而吸引，过低的价格总是被人关注的，可是低价格的背后是什么呢?是陷阱，那植发价格中的陷阱   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/jptj/0116_198.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421391664',
    'updatetime' => '1421906335',
  ),
  196 => 
  array (
    'id' => '196',
    'catid' => '51',
    'typeid' => '0',
    'title' => '植发效果如何？从真实的案例看植发效果',
    'style' => '',
    'thumb' => '',
    'keywords' => '效果 案例',
    'description' => '随着植发技术的不断宣传和脱发人群对于脱发解决方案的效果要求不断提升，植发的效果如何也越来越受到脱发患者的关注！虽然在这个广告途径纷   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/jptj/0116_196.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421391513',
    'updatetime' => '1421391908',
  ),
  197 => 
  array (
    'id' => '197',
    'catid' => '51',
    'typeid' => '0',
    'title' => '治疗脱发植发手术还是药物治疗',
    'style' => '',
    'thumb' => '',
    'keywords' => '药物 还是',
    'description' => '日常生活中很多人都面临着脱发困扰，尤其是近年来女性朋友脱发现象越来越严重，这主要和她们经常做发型和染发、烫发有关系。很多人出现脱发   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/jptj/0116_197.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421391549',
    'updatetime' => '1421391611',
  ),
  195 => 
  array (
    'id' => '195',
    'catid' => '51',
    'typeid' => '0',
    'title' => '植发术后要多少时间才能看到效果',
    'style' => '',
    'thumb' => '',
    'keywords' => '效果 时间',
    'description' => '目前医学界普遍认为植发是治疗脱发最快最直接的方法，因此有许多人都通过植发来解决脱发这个大问题。但是，许多人会担心说植发之后需要多久   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/jptj/0116_195.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421391459',
    'updatetime' => '1421391481',
  ),
  194 => 
  array (
    'id' => '194',
    'catid' => '51',
    'typeid' => '0',
    'title' => '植发手术适应症与禁忌证',
    'style' => '',
    'thumb' => '',
    'keywords' => '适应症 禁忌',
    'description' => '一．植发手术适应症　　1 发际线完好的情况下，可用毛发移植术在一定范围内加大头发的密度。　　2 典型男性M字形脱发的患者。　　3 局部脱   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/jptj/0116_194.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421391404',
    'updatetime' => '1421391450',
  ),
  193 => 
  array (
    'id' => '193',
    'catid' => '51',
    'typeid' => '0',
    'title' => '植发手术时间短且无痛苦',
    'style' => '',
    'thumb' => '',
    'keywords' => '无痛苦 时间短',
    'description' => '整形美容，现在的风波是那么的大啊。可是又会有多少人会选择做整形或者美容手术呢?我想不多吧。因为费用是那么的贵。可是头发移植手术的费   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/jptj/0116_193.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421391357',
    'updatetime' => '1421391391',
  ),
  192 => 
  array (
    'id' => '192',
    'catid' => '51',
    'typeid' => '0',
    'title' => '植发手术如何从根本上解决脱发问题',
    'style' => '',
    'thumb' => '',
    'keywords' => '根本 问题',
    'description' => '植发外科是目前国际上发展迅速的治疗永久性毛发脱失的一新技术。它是将自体残存的头皮优势供区内的部分毛发，通过外科手术的方式使其重新分   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/jptj/0116_192.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421391284',
    'updatetime' => '1421391328',
  ),
  191 => 
  array (
    'id' => '191',
    'catid' => '51',
    'typeid' => '0',
    'title' => '植发手术过程中毫无痛苦',
    'style' => '',
    'thumb' => '',
    'keywords' => '过程',
    'description' => '提到手术，患者都担心手术过程中会非常痛苦，很多想做植发手术的患者也有这样的担心。那么，植发手术过程中会很痛吗？对此专家介绍，植发手   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/jptj/0116_191.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421391227',
    'updatetime' => '1421391264',
  ),
  190 => 
  array (
    'id' => '190',
    'catid' => '51',
    'typeid' => '0',
    'title' => '植发手术的具体过程',
    'style' => '',
    'thumb' => '',
    'keywords' => '过程',
    'description' => '现代人压力巨大，所以很多人都有脱发的现象，大家的形象可谓是巨毁啊，不过还好有植发技术可以弥补这个缺陷。那么大家知道植发的一些常识性   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/jptj/0116_190.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421391171',
    'updatetime' => '1421391216',
  ),
  189 => 
  array (
    'id' => '189',
    'catid' => '51',
    'typeid' => '0',
    'title' => '植发手术安全吗？',
    'style' => '',
    'thumb' => '',
    'keywords' => '植发手术安全吗？',
    'description' => '植发技术可以解决脱发等头发缺陷，相信很多人都有所了解。近年来，植发技术越来越受到大家的关注，那么植发手术到底安全吗？虽然植发技术不   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/jptj/0116_189.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421391097',
    'updatetime' => '1421391141',
  ),
  188 => 
  array (
    'id' => '188',
    'catid' => '51',
    'typeid' => '0',
    'title' => '植发手段与其他治疗手段对比',
    'style' => '',
    'thumb' => '',
    'keywords' => '治疗手段 手段',
    'description' => '1、植发VS米诺地尔治疗　　米诺地尔生发是很多人开始脱发使用的药物，因为米诺地尔生发水对于毛囊有刺激生发的作用、而且副作用小，因此很   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/jptj/0116_188.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421391023',
    'updatetime' => '1421391090',
  ),
  187 => 
  array (
    'id' => '187',
    'catid' => '51',
    'typeid' => '0',
    'title' => '植发机构良莠不齐，如何选择成关键',
    'style' => '',
    'thumb' => '',
    'keywords' => '关键 机构',
    'description' => '植发如今已经成为一种时尚，任何对自己头发不满意的发友都可以进行植发，例如美女们想要植个美人尖、头发加密等，通过正规的植发都取得了不   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/jptj/0116_187.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421390909',
    'updatetime' => '1421390980',
  ),
);
?>