<?php
return array (
  353 => 
  array (
    'id' => '353',
    'catid' => '73',
    'typeid' => '0',
    'title' => '毛囊移植器',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0306/20150306095650820.jpg',
    'keywords' => '毛囊',
    'description' => '毛囊移植器包括空心针头、手术针、推入针装置与针管体；空心针头、手术针与推入装置均设于针管体中，手术针设于推入装置一端并伸入空心针头1中，推入装置控制手术针在空心针头中移动。在使用过程中，在手术针前端空心针头的内孔的容纳管中放入毛囊，将空心针头插入需要植入的部位，按住按钮推动推入针装置，控制手术针向前移动，同时空心针头1后移动，将毛囊留在需要植入的部位；拔出空心针头，完成毛囊移植过程。能够使创口非常小，术后恢复时间短，降低对人体的伤害。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/lxjssb/0205_353.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1423116919',
    'updatetime' => '1425607017',
  ),
  355 => 
  array (
    'id' => '355',
    'catid' => '73',
    'typeid' => '0',
    'title' => '雍禾植发手术室',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0306/20150306095712294.jpg',
    'keywords' => '手术室',
    'description' => '雍禾植发的高端的手术室是医院高端技术的标志之一和重要体现。近年来，雍禾植发不惜斥巨资从德国引进了国际最先进的万级层流技术，打造出亚洲最先进的植发手术室。
手术室采用空气净化层流装置，将空气中的尘埃粒子和细菌高效过滤、消毒。万级层流手术间每立方米沉降菌少于两个，空气清洁度可以达到99 98%，并提供适宜温度，湿度，每小时换气600次以上，创造一个清晰、洁净、舒适、细菌数低的手术空间环境，可以杜绝因手术环境导致的术后感染，提高手术质量。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/lxjssb/0205_355.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1423117034',
    'updatetime' => '1425607036',
  ),
  354 => 
  array (
    'id' => '354',
    'catid' => '73',
    'typeid' => '0',
    'title' => '自主研发植发手术器械',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0306/20150306095731356.jpg',
    'keywords' => '自主研发 器械',
    'description' => '雍禾植发所使用的植发手术器械，包括一次性取发器探头、一次性宝石刀、一次性毛囊分离精细无损刀片及针头、头发加密种植微针、一次性种植镊子、一次性植眉笔等等，均是雍禾植发自主研发，按照研发的要求，向医疗器械生产厂家定制生产，其中头发加密微针向德国医疗器械厂家定制生产。雍禾植发自主研发的一次性毛囊单位取发器探头，是中国唯一能够完整提取毛囊单位，且无损伤的器械。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/lxjssb/0205_354.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1423116982',
    'updatetime' => '1425607056',
  ),
  352 => 
  array (
    'id' => '352',
    'catid' => '73',
    'typeid' => '0',
    'title' => '微动力毛囊单位提取机',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0306/20150306095751980.jpg',
    'keywords' => '毛囊 单位 动力',
    'description' => '微动力毛囊单位提取机及独特的雍禾APL2 0探头是目前国内外较为先进的毛囊提取设备，此设备继承了FUE毛囊提取的优点：不切头皮，不留瘢痕。采用精密度最适合中国人毛囊直径的雍禾APL2 0探头，微动力提取毛囊，避免了传统手术人工提取造成的毛囊损伤，提升了毛囊的成活率，取发速度大约比传统的FUE提高3到5倍。
这意味着，在取毛囊过程中，毛囊离体时间更短，成活率更高；损伤少，提取时对周边毛囊损伤为0。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/lxjssb/0205_352.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1423116743',
    'updatetime' => '1425607074',
  ),
  351 => 
  array (
    'id' => '351',
    'catid' => '73',
    'typeid' => '0',
    'title' => '毛囊分离专用显微镜',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0306/20150306095808786.jpg',
    'keywords' => '毛囊 显微镜',
    'description' => '毛囊分离过程是非常精细的操作，肉眼下分离毛囊，毛囊的损失率高达20-30%。为了避免毛囊资源的浪费，利用毛囊分离专用显微镜对毛囊进行分离已被认定为植发领域中的必备技术。在高倍显微镜下分离毛囊，在放大10-20倍的状态下进行分离，可以准确把握毛囊的位置，准确率高达100%，是肉眼下分离无法比拟的。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/lxjssb/0205_351.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1423116669',
    'updatetime' => '1425607092',
  ),
  350 => 
  array (
    'id' => '350',
    'catid' => '73',
    'typeid' => '0',
    'title' => '头皮显微检测系统',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0306/20150306095829107.jpg',
    'keywords' => '检测系统 头皮',
    'description' => '在术前利用专业毛囊检测仪等设备对发友的毛发状况进行全面的评估，不仅可鉴定发友脱发的级别，得出患者所需要补充的头发数量，在一个范围内标记毫毛，头发根数，系统自动计算头发的密度；同时系统具有头发直径检测功能，根椐毛发的直径和密度，指导医生判断供毛囊区的范围大小，可以任意角度的分析观察，帮助医生更直观精确制定出治疗方案。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/lxjssb/0205_350.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1423116532',
    'updatetime' => '1425607112',
  ),
);
?>