<?php
return array (
  374 => 
  array (
    'id' => '374',
    'catid' => '94',
    'typeid' => '0',
    'title' => '判断植发效果完美的四个标题五',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011345968.jpg',
    'keywords' => '植发 效果 标题',
    'description' => '判断植发效果完美的四个标题五判断植发效果完美的四个标题五判断植发效果完美的四个标题五判断植发效果完美的四个标题五判断植发效果完美的四个标题五判断植发效果完美的四个标题五判断植发效果完美的四个标题五判断植发效果完美的四个标题五判断植发效果完美的四个标题五判断植发效果完美的四个标题五判断植发效果完美的四个标题五判断植发效果完美的四个标题五判断植发效果完美的四个标题五',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/fyywjd/0228_374.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425102075',
    'updatetime' => '1425102113',
  ),
  378 => 
  array (
    'id' => '378',
    'catid' => '94',
    'typeid' => '0',
    'title' => '判断植发效果完美的四个标题六',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011509660.jpg',
    'keywords' => '植发 效果 标题',
    'description' => '判断植发效果完美的四个标题六判断植发效果完美的四个标题六判断植发效果完美的四个标题六判断植发效果完美的四个标题六判断植发效果完美的四个标题六判断植发效果完美的四个标题六判断植发效果完美的四个标题六判断植发效果完美的四个标题六判断植发效果完美的四个标题六判断植发效果完美的四个标题六判断植发效果完美的四个标题六',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/fyywjd/0228_378.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425102184',
    'updatetime' => '1425102212',
  ),
  382 => 
  array (
    'id' => '382',
    'catid' => '94',
    'typeid' => '0',
    'title' => '判断植发效果完美的四个标题七',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011355366.jpg',
    'keywords' => '植发 效果 标题',
    'description' => '判断植发效果完美的四个标题七判断植发效果完美的四个标题七判断植发效果完美的四个标题七判断植发效果完美的四个标题七判断植发效果完美的四个标题七判断植发效果完美的四个标题七判断植发效果完美的四个标题七判断植发效果完美的四个标题七判断植发效果完美的四个标题七',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/fyywjd/0228_382.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425102258',
    'updatetime' => '1425102282',
  ),
  385 => 
  array (
    'id' => '385',
    'catid' => '94',
    'typeid' => '0',
    'title' => '判断植发效果完美的四个标题八',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011509660.jpg',
    'keywords' => '植发 效果 标题',
    'description' => '判断植发效果完美的四个标题八判断植发效果完美的四个标题八判断植发效果完美的四个标题八判断植发效果完美的四个标题八判断植发效果完美的四个标题八判断植发效果完美的四个标题八判断植发效果完美的四个标题八判断植发效果完美的四个标题八判断植发效果完美的四个标题八判断植发效果完美的四个标题八判断植发效果完美的四个标题八判断植发效果完美的四个标题八判断植发效果完美的四个标题八判断植发效果完美的四个标题八判断植发效果完美的四个标题八判断植发效果完美',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/fyywjd/0228_385.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425102297',
    'updatetime' => '1425102323',
  ),
  388 => 
  array (
    'id' => '388',
    'catid' => '94',
    'typeid' => '0',
    'title' => '判断植发效果完美的四个标题九',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011404328.jpg',
    'keywords' => '植发 效果 标题',
    'description' => '判断植发效果完美的四个标题九判断植发效果完美的四个标题九判断植发效果完美的四个标题九判断植发效果完美的四个标题九判断植发效果完美的四个标题九判断植发效果完美的四个标题九判断植发效果完美的四个标题九判断植发效果完美的四个标题九判断植发效果完美的四个标题九判断植发效果完美的四个标题九判断植发效果完美的四个标题九判断植发效果完美的四个标题九判断植发效果完美的四个标题九判断植发效果完美的四个标题九判断植发效果完美的四个标题九判断植发效果完美',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/fyywjd/0228_388.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425102327',
    'updatetime' => '1425102355',
  ),
  391 => 
  array (
    'id' => '391',
    'catid' => '94',
    'typeid' => '0',
    'title' => '判断植发效果完美的四个标题十',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011345968.jpg',
    'keywords' => '植发 效果 标题',
    'description' => '判断植发效果完美的四个标题十判断植发效果完美的四个标题十判断植发效果完美的四个标题十判断植发效果完美的四个标题十判断植发效果完美的四个标题十判断植发效果完美的四个标题十判断植发效果完美的四个标题十判断植发效果完美的四个标题十判断植发效果完美的四个标题十判断植发效果完美的四个标题十判断植发效果完美的四个标题十判断植发效果完美的四个标题十判断植发效果完美的四个标题十判断植发效果完美的四个标题十判断植发效果完美的四个标题十',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/fyywjd/0228_391.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425102395',
    'updatetime' => '1425102423',
  ),
);
?>