<?php
return array (
  19 => 
  array (
    'id' => '19',
    'content' => '这是每一位发友形象蜕变前的必经之路，你看他淡定、坦然的走进手术间，你看手术台上植发专家的一丝不苟，植发手术不再雾里看花',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0" height="400" width="700"><param name="quality" value="high" /><param name="movie" value="http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78312938&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" /><embed height="400" pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78312938&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" type="application/x-shockwave-flash" width="700"></embed></object>',
    'catid' => '33',
    'typeid' => '0',
    'title' => '龙先生手术直播视频简介',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0117/20150117062821954.jpg',
    'keywords' => '手术直播 先生 简介',
    'description' => '这是每一位发友形象蜕变前的必经之路，你看他淡定、坦然的走进手术间，你看手术台上植发专家的一丝不苟，植发手术不再雾里看花',
    'posids' => '1',
    'url' => 'http://bjshenniao.zhifa.cc/yongheshipin/0117_19.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421490580',
    'updatetime' => '1423292167',
  ),
  15 => 
  array (
    'id' => '15',
    'content' => '冯先生手术直播视频简介',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0" height="400" width="700"><param name="quality" value="high" /><param name="movie" value="http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78314457&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" /><embed height="400" pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78314457&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" type="application/x-shockwave-flash" width="700"></embed></object>',
    'catid' => '33',
    'typeid' => '0',
    'title' => '冯先生手术直播视频简介',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0117/20150117060856520.jpg',
    'keywords' => '手术直播 先生 简介',
    'description' => '冯先生手术直播视频简介
',
    'posids' => '1',
    'url' => 'http://bjshenniao.zhifa.cc/yongheshipin/0117_15.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421489107',
    'updatetime' => '1423277940',
  ),
  17 => 
  array (
    'id' => '17',
    'content' => '李先生手术直播视频简介',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0" height="400" width="700"><param name="quality" value="high" /><param name="movie" value="http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78312937&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" /><embed height="400" pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78312937&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" type="application/x-shockwave-flash" width="700"></embed></object>',
    'catid' => '33',
    'typeid' => '0',
    'title' => '李先生手术直播视频简介',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0117/20150117062643876.jpg',
    'keywords' => '手术直播 先生 简介',
    'description' => '李先生手术直播视频简介
',
    'posids' => '1',
    'url' => 'http://bjshenniao.zhifa.cc/yongheshipin/0117_17.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421490374',
    'updatetime' => '1423277916',
  ),
  18 => 
  array (
    'id' => '18',
    'content' => '<div>林先生手术直播视频简介</div>
<div>&nbsp;</div>
',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0" height="400" width="700"><param name="quality" value="high" /><param name="movie" value="http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78313334&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" /><embed height="400" pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78313334&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" type="application/x-shockwave-flash" width="700"></embed></object>',
    'catid' => '33',
    'typeid' => '0',
    'title' => '林先生手术直播视频简介',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0117/20150117062722981.jpg',
    'keywords' => '手术直播 先生 简介',
    'description' => '林先生手术直播视频简介
',
    'posids' => '1',
    'url' => 'http://bjshenniao.zhifa.cc/yongheshipin/0117_18.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421490416',
    'updatetime' => '1423277896',
  ),
  20 => 
  array (
    'id' => '20',
    'content' => '罗先生手术直播视频简介',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0" height="400" width="700"><param name="quality" value="high" /><param name="movie" value="http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78313335&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" /><embed height="400" pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78313335&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" type="application/x-shockwave-flash" width="700"></embed></object>',
    'catid' => '33',
    'typeid' => '0',
    'title' => '罗先生手术直播视频简介',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0117/20150117063027153.jpg',
    'keywords' => '手术直播 简介 视频',
    'description' => '罗先生手术直播视频简介
',
    'posids' => '1',
    'url' => 'http://bjshenniao.zhifa.cc/yongheshipin/0117_20.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421490609',
    'updatetime' => '1423277837',
  ),
  21 => 
  array (
    'id' => '21',
    'content' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="http://www.zhifa.cn/video/zfsszbsp/2014/0308/714.html" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="http://www.zhifa.cn/video/zfsszbsp/2014/0308/714.html" type="application/x-shockwave-flash"></embed></object>',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0" height="400" width="700"><param name="quality" value="high" /><param name="movie" value="http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78313336&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" /><embed height="400" pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78313336&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" type="application/x-shockwave-flash" width="700"></embed></object>',
    'catid' => '33',
    'typeid' => '0',
    'title' => '秦先生手术直播视频简介',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0122/20150122022509659.jpg',
    'keywords' => '手术直播 先生 简介',
    'description' => '秦先生手术直播视频简介',
    'posids' => '1',
    'url' => 'http://bjshenniao.zhifa.cc/yongheshipin/0117_21.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421490651',
    'updatetime' => '1423277813',
  ),
);
?>