<?php
return array (
  180 => 
  array (
    'id' => '180',
    'catid' => '51',
    'typeid' => '0',
    'title' => '常见的植发后的注意事项',
    'style' => '',
    'thumb' => '',
    'keywords' => '注意事项 常见',
    'description' => '其实植发人士在进行了植发手术之后，为了保证手术的成功性和植发人士的康复性，许多事项都是需要植发人士来做的。那么都有什么植发的注意事   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/jptj/0116_180.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421389607',
    'updatetime' => '1421389646',
  ),
  181 => 
  array (
    'id' => '181',
    'catid' => '51',
    'typeid' => '0',
    'title' => '大多生发药不靠谱可能致癌',
    'style' => '',
    'thumb' => '',
    'keywords' => '大多生发药不靠谱可能致癌',
    'description' => '前不久，美国食品和药品管理局(FDA)发布了一项关于生发药的安全信息---目前治疗脱发最常用的5&amp;alpha;还原酶抑制剂可能增加服药者患前列腺癌   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/jptj/0116_181.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421390303',
    'updatetime' => '1421390387',
  ),
  182 => 
  array (
    'id' => '182',
    'catid' => '51',
    'typeid' => '0',
    'title' => '毛发移植术前后注意事项',
    'style' => '',
    'thumb' => '',
    'keywords' => '移植术 毛发 注意事项',
    'description' => '人们越来越喜欢植发手术了，因为它的好的效果是很受欢迎的，可是还会有人对此担心，害怕有什么副作用，专家说只要能够做到一些注意的方面还   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/jptj/0116_182.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421390398',
    'updatetime' => '1421390466',
  ),
  183 => 
  array (
    'id' => '183',
    'catid' => '51',
    'typeid' => '0',
    'title' => '毛发种植的常见疑问解答',
    'style' => '',
    'thumb' => '',
    'keywords' => '毛发 疑问 常见',
    'description' => '毛发种植的方面有很多，比如头发种植，比如睫毛种植，比如胡须种植等等。当然大家对这个整形项目的疑问也是存在的，现在我们一起来看看这些   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/jptj/0116_183.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421390516',
    'updatetime' => '1421390581',
  ),
  184 => 
  array (
    'id' => '184',
    'catid' => '51',
    'typeid' => '0',
    'title' => '毛发种植术前牢记七个事项',
    'style' => '',
    'thumb' => '',
    'keywords' => '毛发 事项',
    'description' => '生活在都市生活中，生活的压力逐渐增大，脱发的现象也越来越多，年纪不大却出现了秃顶的情况，这让人十分苦恼。毛发种植随之十分流行，为很   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/jptj/0116_184.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421390612',
    'updatetime' => '1421390648',
  ),
  185 => 
  array (
    'id' => '185',
    'catid' => '51',
    'typeid' => '0',
    'title' => '如何判定脱发是否可治愈？',
    'style' => '',
    'thumb' => '',
    'keywords' => '如何判定脱发是否可治愈？',
    'description' => '毛发脱落后能否再生，可以将毛发的脱落分为永久性脱发和暂时性脱发两类。　　1 永久性脱发　　如果毛发的脱落是由于毛囊被破坏或是局部皮肤   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/jptj/0116_185.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421390742',
    'updatetime' => '1421390794',
  ),
  186 => 
  array (
    'id' => '186',
    'catid' => '51',
    'typeid' => '0',
    'title' => '植发到底需要多少费用',
    'style' => '',
    'thumb' => '',
    'keywords' => '费用',
    'description' => '你了解植发整形方面的问题吗？众所周知，植发是一种攸关到毛发方面的整形工作，毛发的精细也要求了植发整形的高技术。如今植发技术也以它的   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/jptj/0116_186.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421390836',
    'updatetime' => '1421390886',
  ),
  187 => 
  array (
    'id' => '187',
    'catid' => '51',
    'typeid' => '0',
    'title' => '植发机构良莠不齐，如何选择成关键',
    'style' => '',
    'thumb' => '',
    'keywords' => '关键 机构',
    'description' => '植发如今已经成为一种时尚，任何对自己头发不满意的发友都可以进行植发，例如美女们想要植个美人尖、头发加密等，通过正规的植发都取得了不   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/jptj/0116_187.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421390909',
    'updatetime' => '1421390980',
  ),
);
?>