<?php
return array (
  120 => 
  array (
    'id' => '120',
    'content' => 'http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '129|145|161|177|193|209',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="​​​​​http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="​​​​​http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" type="application/x-shockwave-flash"></embed></object>',
    'catid' => '177',
    'typeid' => '0',
    'title' => '发友会视频标题七',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0319/20150319032912207.jpg',
    'keywords' => '标题 视频',
    'description' => '发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七发友会视频标题七',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/whfyhsp/0323_120.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427077637',
    'updatetime' => '1427077719',
  ),
  113 => 
  array (
    'id' => '113',
    'content' => 'http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '129|145|161|177|193|209',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="​​​​http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="​​​​http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" type="application/x-shockwave-flash"></embed></object>',
    'catid' => '177',
    'typeid' => '0',
    'title' => '发友会视频标题六发友会视频标题六发友会视频标题六',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0319/20150319032912207.jpg',
    'keywords' => '六发 标题 视频',
    'description' => '发友会视频标题六发友会视频标题六发友会视频标题六发友会视频标题六发友会视频标题六发友会视频标题六发友会视频标题六发友会视频标题六发友会视频标题六发友会视频标题六发友会视频标题六发友会视频标题六发友会视频标题六发友会视频标题六发友会视频标题六发友会视频标题六发友会视频标题六发友会视频标题六发友会视频标题六发友会视频标题六发友会视频标题六发友会视频标题六发友会视频标题六发友会视频标题六发友会视频标题六',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/whfyhsp/0323_113.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427077561',
    'updatetime' => '1427077630',
  ),
  106 => 
  array (
    'id' => '106',
    'content' => 'http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '129|145|161|177|193|209',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="​​​http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="​​​http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" type="application/x-shockwave-flash"></embed></object>',
    'catid' => '177',
    'typeid' => '0',
    'title' => '发友会视频标题五发友会视频标题五发友会视频标题五发友',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0319/20150319032820418.jpg',
    'keywords' => '五发 标题 视频',
    'description' => '发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五发友会视频标题五',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/whfyhsp/0323_106.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427077495',
    'updatetime' => '1427077554',
  ),
  99 => 
  array (
    'id' => '99',
    'content' => 'http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '113|129|145|161|177|193|209',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="​​http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="​​http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" type="application/x-shockwave-flash"></embed></object>',
    'catid' => '177',
    'typeid' => '0',
    'title' => '发友会视频标题四发友会视频标题四发友会视频标题四',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0319/20150319033308255.jpg',
    'keywords' => '标题 视频',
    'description' => '发友会视频标题四发友会视频标题四发友会视频标题四发友会视频标题四发友会视频标题四发友会视频标题四发友会视频标题四发友会视频标题四发友会视频标题四发友会视频标题四发友会视频标题四发友会视频标题四发友会视频标题四发友会视频标题四发友会视频标题四发友会视频标题四发友会视频标题四发友会视频标题四发友会视频标题四发友会视频标题四发友会视频标题四发友会视频标题四发友会视频标题四发友会视频标题四',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/whfyhsp/0323_99.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427077422',
    'updatetime' => '1427077489',
  ),
  89 => 
  array (
    'id' => '89',
    'content' => '发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '129|145|161|177|193|209',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" type="application/x-shockwave-flash"></embed></object>',
    'catid' => '177',
    'typeid' => '0',
    'title' => '发友会视频标题一发友会视频标题一发友会视频标题一发友',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0319/20150319033308255.jpg',
    'keywords' => '标题 视频',
    'description' => '发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一发友会视频标题一',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/whfyhsp/0323_89.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427077190',
    'updatetime' => '1427077304',
  ),
);
?>