<?php
return array (
  616 => 
  array (
    'id' => '616',
    'catid' => '225',
    'typeid' => '0',
    'title' => '今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0323/20150323104415317.jpg',
    'keywords' => '要闻 标题',
    'description' => '今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六今日要闻标题六',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/cdjryw/0323_616.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427111168',
    'updatetime' => '1427111197',
  ),
  615 => 
  array (
    'id' => '615',
    'catid' => '225',
    'typeid' => '0',
    'title' => '今日要闻标题五今日要闻标题五今日要闻标题五今日要闻标',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0323/20150323105715326.jpg',
    'keywords' => '要闻 标题',
    'description' => '今日要闻标题五今日要闻标题五今日要闻标题五今日要闻标题五今日要闻标题五今日要闻标题五今日要闻标题五今日要闻标题五今日要闻标题五今日要闻标题五今日要闻标题五今日要闻标题五今日要闻标题五今日要闻标题五今日要闻标题五今日要闻标题五今日要闻标题五今日要闻标题五今日要闻标题五今日要闻标题五今日要闻标题五今日要闻标题五今日要闻标题五今日要闻标题五',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/cdjryw/0323_615.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427111143',
    'updatetime' => '1427111162',
  ),
  614 => 
  array (
    'id' => '614',
    'catid' => '225',
    'typeid' => '0',
    'title' => '今日要闻标题四今日要闻标题四今日要闻标题四',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0323/20150323104415317.jpg',
    'keywords' => '要闻 标题',
    'description' => '今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四今日要闻标题四',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/cdjryw/0323_614.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427111098',
    'updatetime' => '1427111136',
  ),
  613 => 
  array (
    'id' => '613',
    'catid' => '225',
    'typeid' => '0',
    'title' => '今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0323/20150323105553740.jpg',
    'keywords' => '要闻 标题',
    'description' => '今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三今日要闻标题三',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/cdjryw/0323_613.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427111074',
    'updatetime' => '1427111092',
  ),
);
?>