<?php
return array (
  639 => 
  array (
    'id' => '639',
    'catid' => '127',
    'typeid' => '0',
    'title' => '植发手术的具体过程',
    'style' => '',
    'thumb' => '',
    'keywords' => '植发 过程',
    'description' => '现代人压力巨大，所以很多人都有脱发的现象，大家的形象可谓是巨毁啊，不过还好有植发技术可以弥补这个缺陷。那么大家知道植发的一些常识性   ',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/bjrdwz/0324_639.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1427188810',
    'updatetime' => '1427188843',
  ),
  638 => 
  array (
    'id' => '638',
    'catid' => '127',
    'typeid' => '0',
    'title' => '植发手术安全吗？',
    'style' => '',
    'thumb' => '',
    'keywords' => '植发',
    'description' => '植发技术可以解决脱发等头发缺陷，相信很多人都有所了解。近年来，植发技术越来越受到大家的关注，那么植发手术到底安全吗？虽然植发技术不   ',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/bjrdwz/0324_638.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1427188685',
    'updatetime' => '1427188705',
  ),
  637 => 
  array (
    'id' => '637',
    'catid' => '127',
    'typeid' => '0',
    'title' => '植发手段与其他治疗手段对比',
    'style' => '',
    'thumb' => '',
    'keywords' => '植发 治疗手段 手段',
    'description' => '1、植发VS米诺地尔治疗米诺地尔生发是很多人开始脱发使用的药物，因为米诺地尔生发水对于毛囊有刺激生发的作用、而且副作用小，因此很多人   ',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/bjrdwz/0324_637.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1427188651',
    'updatetime' => '1427188674',
  ),
  636 => 
  array (
    'id' => '636',
    'catid' => '127',
    'typeid' => '0',
    'title' => '植发机构良莠不齐，如何选择成关键',
    'style' => '',
    'thumb' => '',
    'keywords' => '植发 关键 机构',
    'description' => '植发如今已经成为一种时尚，任何对自己头发不满意的发友都可以进行植发，例如美女们想要植个美人尖、头发加密等，通过正规的植发都取得了不   ',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/bjrdwz/0324_636.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1427188563',
    'updatetime' => '1427188600',
  ),
  635 => 
  array (
    'id' => '635',
    'catid' => '127',
    'typeid' => '0',
    'title' => '植发到底需要多少费用',
    'style' => '',
    'thumb' => '',
    'keywords' => '植发 费用',
    'description' => '你了解植发整形方面的问题吗？众所周知，植发是一种攸关到毛发方面的整形工作，毛发的精细也要求了植发整形的高技术。如今植发技术也以它的   ',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/bjrdwz/0324_635.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1427188500',
    'updatetime' => '1427188532',
  ),
  634 => 
  array (
    'id' => '634',
    'catid' => '127',
    'typeid' => '0',
    'title' => '如何判定脱发是否可治愈？',
    'style' => '',
    'thumb' => '',
    'keywords' => '如何判定脱发是否可治愈？',
    'description' => '毛发脱落后能否再生，可以将毛发的脱落分为永久性脱发和暂时性脱发两类。1 永久性脱发如果毛发的脱落是由于毛囊被破坏或是局部皮肤发生萎缩   ',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/bjrdwz/0324_634.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1427188361',
    'updatetime' => '1427188403',
  ),
  633 => 
  array (
    'id' => '633',
    'catid' => '127',
    'typeid' => '0',
    'title' => '毛发种植术前牢记七个事项',
    'style' => '',
    'thumb' => '',
    'keywords' => '毛发 事项',
    'description' => '生活在都市生活中，生活的压力逐渐增大，脱发的现象也越来越多，年纪不大却出现了秃顶的情况，这让人十分苦恼。毛发种植随之十分流行，为很   ',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/bjrdwz/0324_633.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1427188042',
    'updatetime' => '1427188069',
  ),
  632 => 
  array (
    'id' => '632',
    'catid' => '127',
    'typeid' => '0',
    'title' => '毛发种植的常见疑问解答',
    'style' => '',
    'thumb' => '',
    'keywords' => '毛发 疑问 常见',
    'description' => '毛发种植的方面有很多，比如头发种植，比如睫毛种植，比如胡须种植等等。当然大家对这个整形项目的疑问也是存在的，现在我们一起来看看这些   ',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/bjrdwz/0324_632.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1427187149',
    'updatetime' => '1427187934',
  ),
  631 => 
  array (
    'id' => '631',
    'catid' => '127',
    'typeid' => '0',
    'title' => '毛发移植术前后注意事项',
    'style' => '',
    'thumb' => '',
    'keywords' => '移植术 毛发 注意事项',
    'description' => '人们越来越喜欢植发手术了，因为它的好的效果是很受欢迎的，可是还会有人对此担心，害怕有什么副作用，专家说只要能够做到一些注意的方面还   ',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/bjrdwz/0324_631.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1427186487',
    'updatetime' => '1427186524',
  ),
  630 => 
  array (
    'id' => '630',
    'catid' => '127',
    'typeid' => '0',
    'title' => '大多生发药不靠谱可能致癌',
    'style' => '',
    'thumb' => '',
    'keywords' => '大多生发药不靠谱可能致癌',
    'description' => '《生命时报》2014年01月14日的消息前不久，美国食品和药品管理局(FDA)发布了一项关于生发药的安全信息---目前治疗脱发最常用的5&amp;alpha;还原   ',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/bjrdwz/0324_630.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1427186329',
    'updatetime' => '1427186359',
  ),
);
?>