<?php
return array (
  46 => 
  array (
    'id' => '46',
    'catid' => '13',
    'typeid' => '0',
    'title' => '疤痕部位可以进行植发吗',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0109/20150109020758413.jpg',
    'keywords' => '疤痕 部位',
    'description' => '植发专家告诉我们只要是疤痕部位能推动，推动会变红，就代表这有血运，只要是有血运存在，那就可以植发。如果是没有血运，属于没有营养的“土地”，种植上去的头发也无法存活。疤痕植发和正常的植发一样，可能更多的是注意我们疤痕部分现在适不适合植发。我们大疤痕在额头或侧头部，也可能在眉间，男性朋友胡须部位等的疤痕我们要根据不同部位不同毛发的特点更加有针对性选取毛发。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/bhzf/0109_46.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1420793370',
    'updatetime' => '1421464160',
  ),
  45 => 
  array (
    'id' => '45',
    'catid' => '13',
    'typeid' => '0',
    'title' => '疤痕毛发移植的效果有保障吗',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0109/20150109020325314.jpg',
    'keywords' => '毛发 疤痕 效果',
    'description' => '疤痕毛发移植手术会很好地解决大家疤痕性脱发烦恼，但还很多人对这种手术的效果不了解，担心手术后没有什么保障。接下来就请雍禾植发专家为   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/bhzf/0109_45.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1420793345',
    'updatetime' => '1421464831',
  ),
  44 => 
  array (
    'id' => '44',
    'catid' => '13',
    'typeid' => '0',
    'title' => '疤痕植发的安全性怎么样',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0109/20150109020758413.jpg',
    'keywords' => '疤痕 安全性',
    'description' => '头发位于人体至高的位置，而头发有疤痕会给一个人的形象大打折扣。因此很多头上有疤痕的人很想通过植发改变，但是不知道疤痕植发是否安全，   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/bhzf/0109_44.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1420793323',
    'updatetime' => '1421465395',
  ),
  43 => 
  array (
    'id' => '43',
    'catid' => '13',
    'typeid' => '0',
    'title' => '疤痕植发让你重新恢复自信',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0109/20150109020857793.jpg',
    'keywords' => '疤痕',
    'description' => '生活中难免会有意外，在雍禾植发我们常常遇到很多疤痕发友都是因为一个意外，或是小的时候头上生疮，而当时医疗环境不好，自身又没有重视，最后发生了感染而导致的大面积疤痕脱发。意外烧烫伤车祸等也很多，因为这些意外创伤后而给发友留下秃发，有些能够遮掩着，有些只能裸露在外，给生活和工作乃至婚姻无疑都造成了无时无刻的心悸和无法形容的痛苦。因在大面积疤痕上能成功进行高密度的疤痕植发手术而享誉海内外，是疤痕脱发发友们的最佳选择。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/bhzf/0109_43.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1420793296',
    'updatetime' => '1421469190',
  ),
  241 => 
  array (
    'id' => '241',
    'catid' => '13',
    'typeid' => '0',
    'title' => '疤痕植发手术的效果好吗？',
    'style' => '',
    'thumb' => '',
    'keywords' => '疤痕 效果',
    'description' => '头部有疤痕导致头发无法正常生长，这会严重的影响患者的个人形象的，尤其是爱美人士更加不能忍受。那么大家要如何解决这一问题呢?疤痕植发   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/bhzf/0117_241.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421469241',
    'updatetime' => '1421469354',
  ),
  242 => 
  array (
    'id' => '242',
    'catid' => '13',
    'typeid' => '0',
    'title' => '不同疤痕脱发手术时间选择不同',
    'style' => '',
    'thumb' => '',
    'keywords' => '疤痕 时间',
    'description' => '大家都知道，疤痕性脱发的原因有很多，但归类而言，主要就分为两类，一类是外伤造成的疤痕性脱发，另一种是由于患者自身的皮肤免疫性疾病发炎所造成的。由于两种不同的原因，所以选择的手术方式也是有所不同的，那么对于疤痕性植发手术应该如何选择呢?雍禾植发专家指出，治疗疤痕脱发，最好的方法就是疤痕植发手术(FUE-APL2 0无痕植发技术)，不仅可以使疤痕部位的毛发再生，而且对疤痕也有一定的改善作用。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/bhzf/0117_242.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421469367',
    'updatetime' => '1421469447',
  ),
  243 => 
  array (
    'id' => '243',
    'catid' => '13',
    'typeid' => '0',
    'title' => '头部疤痕选择毛发移植不再自卑',
    'style' => '',
    'thumb' => '',
    'keywords' => '毛发 疤痕 头部',
    'description' => '人都是爱美的，特别是女性，没有谁不希望自己的外貌漂漂亮亮的。可是生活中，并不是每个人都能如愿，有那样一些人，就因为各种各样的意外而   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/bhzf/0117_243.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421469463',
    'updatetime' => '1421469580',
  ),
  244 => 
  array (
    'id' => '244',
    'catid' => '13',
    'typeid' => '0',
    'title' => '头上有疤痕怎么办?',
    'style' => '',
    'thumb' => '',
    'keywords' => '疤痕 怎么办',
    'description' => '
雍禾植发专家指出，要进行疤痕植发手术是有一定的先决条件的。皮肤的自体免疫性疾病发炎所造成的疤痕性脱发，一般需要在这些发炎疾病受到完全控制后一年，才可以考虑是否可以做疤痕植发手术。而且植发之前还需要经过植发专家的评估，确定是否发炎性疾病已经完全治疗，才可以进行疤痕植发手术。至于外伤，放射治疗及外科手术后所造成的疤痕性脱发，一般最快要在六个月之后，确定受伤的毛囊不会再长出头发才可以进行疤痕植发手术。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/bhzf/0117_244.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421469603',
    'updatetime' => '1421469646',
  ),
);
?>