<?php
return array (
  184 => 
  array (
    'id' => '184',
    'content' => '李先生手术直播视频简介',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78312937&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78312937&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" type="application/x-shockwave-flash"></embed></object>',
    'catid' => '130',
    'typeid' => '0',
    'title' => '李先生手术直播视频简介',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0331/20150331014007793.jpg',
    'keywords' => '手术直播 先生 简介',
    'description' => '',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/szshoushusp/0331_184.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1427780335',
    'updatetime' => '1427780412',
  ),
  166 => 
  array (
    'id' => '166',
    'content' => 'http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '130|146|162|178|194|210',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="​​​​​​​​​​​​http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="​​​​​​​​​​​​http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" type="application/x-shockwave-flash"></embed></object>',
    'catid' => '130',
    'typeid' => '0',
    'title' => '手术视频标题七手术视频标题七手术视频标题七',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0319/20150319033308255.jpg',
    'keywords' => '标题 视频',
    'description' => '手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/szshoushusp/0323_166.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427078309',
    'updatetime' => '1427078372',
  ),
  159 => 
  array (
    'id' => '159',
    'content' => 'http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '130|146|162|178|194|210',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="​​​​​​​​​​​http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="​​​​​​​​​​​http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" type="application/x-shockwave-flash"></embed></object>',
    'catid' => '130',
    'typeid' => '0',
    'title' => '手术视频标题六手术视频标题六手术视频标题六',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0319/20150319033308255.jpg',
    'keywords' => '六手 标题 视频',
    'description' => '手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/szshoushusp/0323_159.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427078239',
    'updatetime' => '1427078302',
  ),
  152 => 
  array (
    'id' => '152',
    'content' => 'http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '130|146|162|178|194|210',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="​​​​​​​​​​http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="​​​​​​​​​​http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" type="application/x-shockwave-flash"></embed></object>',
    'catid' => '130',
    'typeid' => '0',
    'title' => '手术视频标题五手术视频标题五手术视频标题五',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0319/20150319033308255.jpg',
    'keywords' => '标题 视频',
    'description' => '手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/szshoushusp/0323_152.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427078146',
    'updatetime' => '1427078232',
  ),
  145 => 
  array (
    'id' => '145',
    'content' => 'http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '130|146|162|178|194|210',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="​​​​​​​​​http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="​​​​​​​​​http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" type="application/x-shockwave-flash"></embed></object>',
    'catid' => '130',
    'typeid' => '0',
    'title' => '手术视频标题四手术视频标题四手术视频标题四手术视频标',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0319/20150319032912207.jpg',
    'keywords' => '视频 标题',
    'description' => '手术视频标题四手术视频标题四手术视频标题四手术视频标手术视频标题四手术视频标题四手术视频标题四手术视频标手术视频标题四手术视频标题四手术视频标题四手术视频标手术视频标题四手术视频标题四手术视频标题四手术视频标手术视频标题四手术视频标题四手术视频标题四手术视频标',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/szshoushusp/0323_145.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427078042',
    'updatetime' => '1427078138',
  ),
  138 => 
  array (
    'id' => '138',
    'content' => 'http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '130|146|162|178|194|210',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="​​​​​​​​http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="​​​​​​​​http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" type="application/x-shockwave-flash"></embed></object>',
    'catid' => '130',
    'typeid' => '0',
    'title' => '手术视频标题三手术视频标题三手术视频标题三手术视频标',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0319/20150319033308255.jpg',
    'keywords' => '三手 视频 标题',
    'description' => '手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三手术视频标题三',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/szshoushusp/0323_138.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427077957',
    'updatetime' => '1427078036',
  ),
  131 => 
  array (
    'id' => '131',
    'content' => 'http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '130|146|162|178|194|210',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="​​​​​​​http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="​​​​​​​http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" type="application/x-shockwave-flash"></embed></object>',
    'catid' => '130',
    'typeid' => '0',
    'title' => '手术视频标题二手术视频标题二手术视频标题二',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0319/20150319033308255.jpg',
    'keywords' => '标题 视频',
    'description' => '手术视频标题二手术视频标题二手术视频标题二手术视频标题二手术视频标题二手术视频标题二手术视频标题二手术视频标题二手术视频标题二手术视频标题二手术视频标题二手术视频标题二手术视频标题二手术视频标题二手术视频标题二手术视频标题二手术视频标题二手术视频标题二手术视频标题二手术视频标题二手术视频标题二手术视频标题二手术视频标题二',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/szshoushusp/0323_131.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427077882',
    'updatetime' => '1427077951',
  ),
  124 => 
  array (
    'id' => '124',
    'content' => 'http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '130|146|162|178|194|210',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="​​​​​​http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="​​​​​​http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" type="application/x-shockwave-flash"></embed></object>',
    'catid' => '130',
    'typeid' => '0',
    'title' => '手术视频标题一手术视频标题一手术视频标题一手术视频标',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0319/20150319032820418.jpg',
    'keywords' => '一手 视频 标题',
    'description' => '手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一手术视频标题一',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/szshoushusp/0323_124.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427077742',
    'updatetime' => '1427077805',
  ),
);
?>