<?php
return array (
  479 => 
  array (
    'id' => '479',
    'catid' => '101',
    'typeid' => '0',
    'title' => '常见的脱发类型',
    'style' => '',
    'thumb' => '',
    'keywords' => '常见 类型',
    'description' => '　　常见的脱发类型　　现在生活压力的越来越大，导致了很多疾病的发生，脱发就是其中一种常见的疾病，很多明星也同样患有脱发，很大部分原   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/tflxzds/0318_479.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426663834',
    'updatetime' => '1426663861',
  ),
  480 => 
  array (
    'id' => '480',
    'catid' => '101',
    'typeid' => '0',
    'title' => '常见四种脱发类型，你中了哪一种？',
    'style' => '',
    'thumb' => '',
    'keywords' => '常见 类型',
    'description' => '　　常见四种脱发类型，你中了哪一种？　　脱发不是我们所说的癌症，它是可以治愈的。虽然脱发属于疾病，但是它不会伤害我们的身体健康。虽   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/tflxzds/0318_480.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426663887',
    'updatetime' => '1426663915',
  ),
  481 => 
  array (
    'id' => '481',
    'catid' => '101',
    'typeid' => '0',
    'title' => '脱发类型有多少',
    'style' => '',
    'thumb' => '',
    'keywords' => '类型',
    'description' => '　　脂溢性脱发　　脂溢性脱发，是在皮脂溢出过多的基础上发生的一种脱发，常伴有头屑增多，头皮油腻，痛痒明显。多发生于皮脂腺分泌旺盛的   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/tflxzds/0318_481.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426664126',
    'updatetime' => '1426664133',
  ),
  482 => 
  array (
    'id' => '482',
    'catid' => '101',
    'typeid' => '0',
    'title' => '休止期脱发',
    'style' => '',
    'thumb' => '',
    'keywords' => '休止期脱发',
    'description' => '　　当人遭逢过大的压力，如生产、考试或家人去世等重大变故时，毛囊由生长期进入休止期的数目会增加，其比例可高达75%，基于休止期 头发   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/tflxzds/0318_482.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426664165',
    'updatetime' => '1426664188',
  ),
  483 => 
  array (
    'id' => '483',
    'catid' => '101',
    'typeid' => '0',
    'title' => '永久性脱发与暂时性脱发',
    'style' => '',
    'thumb' => '',
    'keywords' => '暂时性 永久性',
    'description' => '　　脱发首先要分清类型，一般脱发可分成两种基本类型，由于毛囊受损造成的永久性脱发，和由于毛囊短时间受损造成的暂时性脱发。永久性脱发   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/tflxzds/0318_483.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426664198',
    'updatetime' => '1426664227',
  ),
  484 => 
  array (
    'id' => '484',
    'catid' => '101',
    'typeid' => '0',
    'title' => '周期性脱发',
    'style' => '',
    'thumb' => '',
    'keywords' => '周期性',
    'description' => '　　一般说来，普通人每天都会有50～100根左右的 头发会掉落。人类毛发的生长是有周期性的，过了成长期之后，毛发会自然掉落，但成长期的   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/tflxzds/0318_484.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426664409',
    'updatetime' => '1426664424',
  ),
  485 => 
  array (
    'id' => '485',
    'catid' => '101',
    'typeid' => '0',
    'title' => '​三种常见的女性脱发类型',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '　　女性脱发近几年来有所增长，并呈现着越来越多的趋势。但女性脱发秃露的形态大多与男性不同，脱落的原因也较为复杂，女性脱发与体内激素   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/tflxzds/0318_485.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426664446',
    'updatetime' => '1426664518',
  ),
  486 => 
  array (
    'id' => '486',
    'catid' => '101',
    'typeid' => '0',
    'title' => 'M型秃发际线高的原因以及如何治疗',
    'style' => '',
    'thumb' => '',
    'keywords' => '发际 原因',
    'description' => '　　随着社会压力的增大，很多疾病都跻身于医学界，脱发就是最常见的疾病之一。目前走在大街上，到处都可以看到M型秃发的情况，这也就造成   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/tflxzds/0318_486.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426664531',
    'updatetime' => '1426664559',
  ),
);
?>