<?php
return array (
  315 => 
  array (
    'id' => '315',
    'catid' => '35',
    'typeid' => '0',
    'title' => '问：头发种植成功率及毛囊的成活率为多少？',
    'style' => '',
    'thumb' => '',
    'keywords' => '成活率 毛囊 成功率',
    'description' => '答：一位临床经验丰富、技术一流的自体头发移植外科医生所操作的头发移植手术成功率为100%，毛囊再植的成活率一般为90%～100%。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/cjwd/0203_315.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1422925822',
    'updatetime' => '1422925853',
  ),
  316 => 
  array (
    'id' => '316',
    'catid' => '35',
    'typeid' => '0',
    'title' => '问：头发种植手术痛苦吗？',
    'style' => '',
    'thumb' => '',
    'keywords' => '问：头发种植手术痛苦吗？',
    'description' => '答：手术采用头皮的局部麻醉，毫无痛苦。术中可以看杂志、VCD、喝饮料、听音乐，手术过程患者感到轻松、舒适。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/cjwd/0203_316.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1422925902',
    'updatetime' => '1422925915',
  ),
  317 => 
  array (
    'id' => '317',
    'catid' => '35',
    'typeid' => '0',
    'title' => '问：头发种植手术时间、术后愈合及术后头发的生长情况如',
    'style' => '',
    'thumb' => '',
    'keywords' => '情况 时间',
    'description' => '答：此手术属于门诊手术，全过程需要3个小时左右。十天后完全恢复正常。术后的3个月移植胚建立起新的营养环境及血循环，新发开始生长。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/cjwd/0203_317.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1422925938',
    'updatetime' => '1422925954',
  ),
  318 => 
  array (
    'id' => '318',
    'catid' => '35',
    'typeid' => '0',
    'title' => '问：移植手术后一些移植胚上的头发脱落是属于正常现象吗',
    'style' => '',
    'thumb' => '',
    'keywords' => '现象',
    'description' => '答：对于脱发不是很严重只需要进行加密手术的患者来说，由于在做头顶部显微切口的过程中不可避免会伤及一些原有头发的发干，在术后的一段时   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/cjwd/0203_318.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1422925967',
    'updatetime' => '1422925981',
  ),
  319 => 
  array (
    'id' => '319',
    'catid' => '35',
    'typeid' => '0',
    'title' => '问：移植手术后的水肿是否属于正常现象？',
    'style' => '',
    'thumb' => '',
    'keywords' => '水肿 现象',
    'description' => '答：一般术后第三天有些病人会在前额、鼻梁处及单侧或双侧眼睑处会出现轻度的水肿。这些水肿一般在3一4天内会消退，故请不必过于担心。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/cjwd/0203_319.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1422926012',
    'updatetime' => '1422926021',
  ),
  320 => 
  array (
    'id' => '320',
    'catid' => '35',
    'typeid' => '0',
    'title' => '问：头发种植后毛囊还会再坏死吗？',
    'style' => '',
    'thumb' => '',
    'keywords' => '毛囊',
    'description' => '答：头发之所以脱落是因为头顶部毛囊与颞枕部毛囊结构不同。额顶部的毛囊具有结构上的先天性缺陷。这些毛囊受后天的多种因素，如：内分泌、   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/cjwd/0203_320.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1422926094',
    'updatetime' => '1422926102',
  ),
  321 => 
  array (
    'id' => '321',
    'catid' => '35',
    'typeid' => '0',
    'title' => '问：雍禾为手术录像如何保密患者隐私?',
    'style' => '',
    'thumb' => '',
    'keywords' => '录像 患者 隐私',
    'description' => '答：雍禾的手术录像是为约束医院的，是一种诚信的保障，录像只有你知我知，不会给第三方传阅，雍禾更不会拿你的手术视频做宣传资料。当然，   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/cjwd/0203_321.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1422926114',
    'updatetime' => '1422926122',
  ),
  322 => 
  array (
    'id' => '322',
    'catid' => '35',
    'typeid' => '0',
    'title' => '问：雍禾植发的不过度医疗包括哪些基本内容?',
    'style' => '',
    'thumb' => '',
    'keywords' => '医疗 内容',
    'description' => '答：雍禾植发的手术费用包括三部分。一是毛囊移植费用，比方说FUE移植2500毛囊单位，每毛囊基本价10元，总共就是25000元。若遇上优惠，总费   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/cjwd/0203_322.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1422926129',
    'updatetime' => '1422926137',
  ),
);
?>