<?php
return array (
  328 => 
  array (
    'id' => '328',
    'catid' => '35',
    'typeid' => '0',
    'title' => '问：雍禾经常资助不同城市的术后发友聚会',
    'style' => '',
    'thumb' => '',
    'keywords' => '城市',
    'description' => '答：只要你是雍禾的术后发友，可以跨地参加雍禾资助的任一发友聚会，这就不一定是6选1，可以是6选2选3选4，甚至是6选6。雍禾定期资助发友旅   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/cjwd/0203_328.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1422926273',
    'updatetime' => '1422926301',
  ),
  327 => 
  array (
    'id' => '327',
    'catid' => '35',
    'typeid' => '0',
    'title' => '问：雍禾的跨地服务包括免费修复或退款吗?',
    'style' => '',
    'thumb' => '',
    'keywords' => '服务包括',
    'description' => '答：包括的。雍禾植发有国内一流的植发技术，按理说不会有手术失败的，也就不存在修复或退款的事情。但有些发友就追问：万一达不到许诺的毛   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/cjwd/0203_327.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1422926255',
    'updatetime' => '1422926265',
  ),
  326 => 
  array (
    'id' => '326',
    'catid' => '35',
    'typeid' => '0',
    'title' => '问：雍禾植发的跨地服务还有哪些主要内容?',
    'style' => '',
    'thumb' => '',
    'keywords' => '内容',
    'description' => '答：除了上面说的以外，雍禾植发的跨地服务还包括术后免费洗头，免费清理血痂，免费复查。一般来说，术后四五天可以洗头，术后9天清理血痂   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/cjwd/0203_326.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1422926229',
    'updatetime' => '1422926242',
  ),
  325 => 
  array (
    'id' => '325',
    'catid' => '35',
    'typeid' => '0',
    'title' => '问：雍禾植发的毛囊成活率是如何保障的？',
    'style' => '',
    'thumb' => '',
    'keywords' => '成活率 毛囊',
    'description' => '答：雍禾植发的毛囊成活率确保95%，也就是说我们为你种植100毛囊单位，确保成活95个毛囊单位。当然，95%只是最低保障，并不是说雍禾植发为   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/cjwd/0203_325.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1422926208',
    'updatetime' => '1422926223',
  ),
);
?>