<?php
return array (
  183 => 
  array (
    'id' => '183',
    'catid' => '114',
    'typeid' => '0',
    'title' => '冯先生手术直播视频简介',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0324/20150324031249302.jpg',
    'keywords' => '手术直播 先生 简介',
    'description' => '冯先生手术直播视频简介',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/bjshoushusp/0324_183.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1427181117',
    'updatetime' => '1427275560',
  ),
  165 => 
  array (
    'id' => '165',
    'catid' => '114',
    'typeid' => '0',
    'title' => '手术视频标题七手术视频标题七手术视频标题七',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0319/20150319033308255.jpg',
    'keywords' => '标题 视频',
    'description' => '手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七手术视频标题七',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/bjshoushusp/0323_165.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427078309',
    'updatetime' => '1427078372',
  ),
  158 => 
  array (
    'id' => '158',
    'catid' => '114',
    'typeid' => '0',
    'title' => '手术视频标题六手术视频标题六手术视频标题六',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0319/20150319033308255.jpg',
    'keywords' => '六手 标题 视频',
    'description' => '手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六手术视频标题六',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/bjshoushusp/0323_158.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427078239',
    'updatetime' => '1427078302',
  ),
  151 => 
  array (
    'id' => '151',
    'catid' => '114',
    'typeid' => '0',
    'title' => '手术视频标题五手术视频标题五手术视频标题五',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0319/20150319033308255.jpg',
    'keywords' => '标题 视频',
    'description' => '手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五手术视频标题五',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/bjshoushusp/0323_151.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427078146',
    'updatetime' => '1427078232',
  ),
);
?>