<?php
return array (
  182 => 
  array (
    'id' => '182',
    'content' => 'http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78314457&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="​​​​​​​http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78314457&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="​​​​​​​http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78314457&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" type="application/x-shockwave-flash"></embed></object>',
    'catid' => '227',
    'typeid' => '0',
    'title' => '  二十岁的年龄四十岁的面容',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0323/20150323105553740.jpg',
    'keywords' => '面容 年龄',
    'description' => '  二十岁的年龄四十岁的面容  二十岁的年龄四十岁的面容  二十岁的年龄四十岁的面容  二十岁的年龄四十岁的面容  二十岁的年龄四十岁的面容  二十岁的年龄四十岁的面容  二十岁的年龄四十岁的面容  二十岁的年龄四十岁的面容  二十岁的年龄四十岁的面容  二十岁的年龄四十岁的面容',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/cdshoushusp/0323_182.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427111646',
    'updatetime' => '1427111669',
  ),
  181 => 
  array (
    'id' => '181',
    'content' => 'http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78314457&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="​​​​​​http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78314457&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="​​​​​​http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78314457&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" type="application/x-shockwave-flash"></embed></object>',
    'catid' => '227',
    'typeid' => '0',
    'title' => '又爱又恨的秀发我该拿你怎么办？',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0323/20150323104248597.jpg',
    'keywords' => '秀发 怎么办',
    'description' => '又爱又恨的秀发我该拿你怎么办？又爱又恨的秀发我该拿你怎么办？又爱又恨的秀发我该拿你怎么办？又爱又恨的秀发我该拿你怎么办？又爱又恨的秀发我该拿你怎么办？又爱又恨的秀发我该拿你怎么办？又爱又恨的秀发我该拿你怎么办？又爱又恨的秀发我该拿你怎么办？又爱又恨的秀发我该拿你怎么办？又爱又恨的秀发我该拿你怎么办？又爱又恨的秀发我该拿你怎么办？又爱又恨的秀发我该拿你怎么办？又爱又恨的秀发我该拿你怎么办？又爱又恨的秀发我该拿你怎么办？又爱又恨的秀发我该拿你怎么办？',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/cdshoushusp/0323_181.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427111618',
    'updatetime' => '1427111642',
  ),
  180 => 
  array (
    'id' => '180',
    'content' => 'http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78314457&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="​​​​​http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78314457&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="​​​​​http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78314457&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" type="application/x-shockwave-flash"></embed></object>',
    'catid' => '227',
    'typeid' => '0',
    'title' => '2级植发案例标题一',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0323/20150323104221666.jpg',
    'keywords' => '植发 案例 标题',
    'description' => '2级植发案例标题一2级植发案例标题一2级植发案例标题一2级植发案例标题一2级植发案例标题一2级植发案例标题一2级植发案例标题一2级植发案例标题一2级植发案例标题一2级植发案例标题一2级植发案例标题一2级植发案例标题一2级植发案例标题一2级植发案例标题一2级植发案例标题一2级植发案例标题一2级植发案例标题一2级植发案例标题一2级植发案例标题一2级植发案例标题一2级植发案例标题一2级植发案例标题一2级植发案例标题一',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/cdshoushusp/0323_180.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427111588',
    'updatetime' => '1427111613',
  ),
  179 => 
  array (
    'id' => '179',
    'content' => 'http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78314457&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="​​​​http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78314457&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="​​​​http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78314457&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" type="application/x-shockwave-flash"></embed></object>',
    'catid' => '227',
    'typeid' => '0',
    'title' => '手术视频标题三手术视频标题三手术视频标题三手术视频标',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0323/20150323104221666.jpg',
    'keywords' => '三手 视频 标题',
    'description' => '手术视频标题三手术视频标题三手术视频标题三手术视频标手术视频标题三手术视频标题三手术视频标题三手术视频标手术视频标题三手术视频标题三手术视频标题三手术视频标手术视频标题三手术视频标题三手术视频标题三手术视频标手术视频标题三手术视频标题三手术视频标题三手术视频标手术视频标题三手术视频标题三手术视频标题三手术视频标手术视频标题三手术视频标题三手术视频标题三手术视频标手术视频标题三手术视频标题三手术视频标题三手术视频标手术视频标题三手术视频标题三手术视频标题三手术视频标手术视频标题三手术视频标题三手术视频标题三手术视频标手术视频标题三手术视频标题三手术视频标题三手术视频标',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/cdshoushusp/0323_179.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427111558',
    'updatetime' => '1427111583',
  ),
  178 => 
  array (
    'id' => '178',
    'content' => 'http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78314457&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="​​​http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78314457&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="​​​http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=78314457&amp;autoplay=false&amp;xuid=0fc134bbcc9d49fx&amp;from=page" type="application/x-shockwave-flash"></embed></object>',
    'catid' => '227',
    'typeid' => '0',
    'title' => '手术视频标题一手术视频标题一手术视频标题一手术视频标',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0323/20150323104236122.jpg',
    'keywords' => '一手 视频 标题',
    'description' => '手术视频标题一手术视频标题一手术视频标题一手术视频标手术视频标题一手术视频标题一手术视频标题一手术视频标手术视频标题一手术视频标题一手术视频标题一手术视频标手术视频标题一手术视频标题一手术视频标题一手术视频标手术视频标题一手术视频标题一手术视频标题一手术视频标手术视频标题一手术视频标题一手术视频标题一手术视频标手术视频标题一手术视频标题一手术视频标题一手术视频标手术视频标题一手术视频标题一手术视频标题一手术视频标手术视频标题一手术视频标题一手术视频标题一手术视频标手术视频标题一手术视频标题一手术视频标题一手术视频标手术视频标题一手术视频标题一手术视频标题一手术视频标手术视频标题一手术视频标题一手术视频标题一手术视频标手术视频标题一手术视频标题一手术视频标题一手术视频标手术视频标题一手术视频标题一手术视频标题一手术视频标手术视频标题一手术视频标题一手术视频标题一手术视频标手术视频标题一手术视频标题一手术视频标题一手术视频标手术视频标题一手术视频标题一手术视频标题一手术视频标手术视频标题一手术视频标题一手术视频标题一手术视频标手术视频标题一手术视频标题一手术视频标题一手术视频标手术视频标题一手术视频标题一手术视频标题一手术视',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/cdshoushusp/0323_178.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427111530',
    'updatetime' => '1427111554',
  ),
);
?>