<?php
return array (
  35 => 
  array (
    'id' => '35',
    'catid' => '11',
    'typeid' => '0',
    'title' => '睫毛的形态与美学',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0109/20150109021056181.jpg',
    'keywords' => '睫毛 标题',
    'description' => '睫毛是眼睑的上下睑缘上生长的两行短毛，正常时整齐排列，排成2~3行，呈半弧形。上下睑缘的睑毛数量并不一致，上睑约100~150根，长约8~12mm，下睑睫毛仅为50~70根，长约6~8mm。睫毛的生长具有一定的方向和倾斜度。上睑睫毛向前上方弯曲伸直，平视闭眼时为1400~1600向上倾斜，平视向上倾斜度为1100~1300。不同民族的人，睫毛的长度和上翘弧度不一样，如我国新疆维吾尔族女性睫毛较长且向上弯曲的弧度大。根据上睫毛的倾斜度，可以将睫毛的形状分为：长翘形睫毛，正直形睫毛和下垂形睫毛',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/jmzz/0109_35.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1420793082',
    'updatetime' => '1421460369',
  ),
  34 => 
  array (
    'id' => '34',
    'catid' => '11',
    'typeid' => '0',
    'title' => '植睫毛，塑造浓密纤长睫毛',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0109/20150109021157652.jpg',
    'keywords' => '睫毛 标题',
    'description' => '化妆必离不开刷睫毛膏，为了就是让睫毛显得又长又翘。那么，对于天生睫毛短小稀疏的朋友们，怎么能做到素颜的时候也能呈现又长又翘的睫毛呢?那如何能从根本上解决睫毛短、稀的问题，从而让眼睫毛浓密纤长呢? 对此，雍禾植发专家解答道，植睫毛就能最有效的解决睫毛短的问题。植睫毛是运用自体毛发移植技术，提取头部后枕部的健康毛囊组织，经过显微镜下对毛囊多余的脂肪组织予以处理后再精细地种植到眼睑上。植睫毛技术不仅应用于美容性质的植睫毛，对重建性的植睫毛手',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/jmzz/0109_34.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1420793061',
    'updatetime' => '1421460532',
  ),
  33 => 
  array (
    'id' => '33',
    'catid' => '11',
    'typeid' => '0',
    'title' => '植睫毛手术，美丽的睫毛翘起来',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0109/20150109021012832.jpg',
    'keywords' => '睫毛 标题',
    'description' => '睫毛是眼睛的保护伞，长长的睫毛，大大的眼睛，是每个女人的梦想，植睫毛可以满足你爱美的心。然而事实却让人气馁，你是否意识到经常使用睫   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/jmzz/0109_33.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1420793036',
    'updatetime' => '1421460666',
  ),
  32 => 
  array (
    'id' => '32',
    'catid' => '11',
    'typeid' => '0',
    'title' => '植睫毛疼吗?',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0109/20150109020758413.jpg',
    'keywords' => '睫毛 标题',
    'description' => '另外，雍禾植发专家提示：一般而言，睫毛移植后五个月左右，新的睫毛就会不断的长出来。由于正常的睫毛毛囊每生长三个月就会休息三个月，而睫毛移植过来的头皮里面的毛囊是生长两三年，才会休息三个月，因此新长出来的睫毛必须要经常修剪，避免长的太长;同时为了让睫毛的卷曲方向有一制性，必须要使用睫毛刷整理新的睫毛，这是在接受睫毛移植的时候必须要注意的。
',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/jmzz/0109_32.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1420793009',
    'updatetime' => '1421460745',
  ),
  31 => 
  array (
    'id' => '31',
    'catid' => '11',
    'typeid' => '0',
    'title' => '植睫毛效果能维持多久?',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0109/20150109020325314.jpg',
    'keywords' => '睫毛 标题',
    'description' => '雍禾植发专家表示，咨询“植睫毛效果能维持多久”问题的发友一定是对植睫毛手术不够了解，所以我们从植睫毛的手术原理来看。植睫毛与眉毛移植、胡须移植等一样，都是植发手术的一种。细心的发友就会发现，一般后枕部的头发不仅要多于其他部位，也不易脱落。其实我们的后枕部的毛囊数量是头顶的两到三倍，而且由于后枕部的毛囊不受雄性激素的影响，具有永久不会脱落的性质。所以大多数人在解决睫毛问题时都会选择植睫毛。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/jmzz/0109_31.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1420792981',
    'updatetime' => '1421460917',
  ),
  232 => 
  array (
    'id' => '232',
    'catid' => '11',
    'typeid' => '0',
    'title' => '植上睫毛让你更加迷人',
    'style' => '',
    'thumb' => '',
    'keywords' => '睫毛',
    'description' => '睫毛虽不及一头秀发那么张扬显眼，然而对眼睛来说却是必不可少的保护屏障。与睫毛的保护作用表现在，上下睑缘睫毛似排排卫士，排列在睑裂边缘。睫毛，是眼睛的第二道防线。任何东西接近眼睛，首先要碰到睫毛，从而立即引起闭眼反射，保护眼球不受外来的侵犯。有遮光，防止灰尘、异物、汗水进入眼内，和眼睑一起对角膜、眼球进行保护的作用。睫毛还能防止紫外线对眼睛的损害。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/jmzz/0117_232.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421460935',
    'updatetime' => '1421461117',
  ),
  233 => 
  array (
    'id' => '233',
    'catid' => '11',
    'typeid' => '0',
    'title' => '种假睫毛不消毒，多为三无产品',
    'style' => '',
    'thumb' => '',
    'keywords' => '睫毛 产品',
    'description' => '    种假睫毛不消毒，多为三无产品。种睫毛才是发友们解决睫毛稀疏问题的最好方法。种睫毛属于高精端的微创性外科手术，手术不过中不需要任何粘合剂，所以，完全不会出现种假睫毛导致的眼皮感染等类似情况。更重要的是，种睫毛手术不仅不会引发感染和过敏，而且采用雍禾植发FUE-APL2 0无痕植发技术，还能保证术后无痕。在此，希望发友们都能明智的选择种睫毛手术。
',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/jmzz/0117_233.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421461155',
    'updatetime' => '1421461231',
  ),
  234 => 
  array (
    'id' => '234',
    'catid' => '11',
    'typeid' => '0',
    'title' => '种植的睫毛需要常年修剪吗?',
    'style' => '',
    'thumb' => '',
    'keywords' => '睫毛 常年',
    'description' => '
睫毛种植是应用显微外科手术技术取出这一部分健康的毛囊组织，经仔细加工培养后按照自然的头发生长方向艺术化地移植于睫毛部位。毛囊存活后便会生长出健康的新发，而且睫毛种植术所长出的新发保持原有头发的一切生物学特性，因此，长出的睫毛就会和头发一样不断的长长。为了美观和方便起见，自然就会需要发友们定期修剪睫毛了。但并不是说进行了睫毛种植后就意味着要常年修剪睫毛。因为种植的睫毛在术后3-5年后就会有睫毛本身的性质，那时就不用再修剪了。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/jmzz/0117_234.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421461245',
    'updatetime' => '1421461304',
  ),
);
?>