<?php
return array (
  342 => 
  array (
    'id' => '342',
    'catid' => '212',
    'typeid' => '0',
    'title' => '这是标题六这是标题六这是标题六',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0323/20150323104415317.jpg',
    'keywords' => '标题 这是',
    'description' => '这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六这是标题六v',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/hzwhfyal_tfzz/0323_342.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427079144',
    'updatetime' => '1427079275',
  ),
  272 => 
  array (
    'id' => '272',
    'catid' => '212',
    'typeid' => '0',
    'title' => '这是标题五这是标题五这是标题五这是标题五这是标题五',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0323/20150323104236122.jpg',
    'keywords' => '标题 这是',
    'description' => '这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/hzwhfyal_tfzz/0323_272.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427079029',
    'updatetime' => '1427079132',
  ),
  202 => 
  array (
    'id' => '202',
    'catid' => '212',
    'typeid' => '0',
    'title' => '这是标题四这是标题四这是标题四这是标题四',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0323/20150323104248597.jpg',
    'keywords' => '标题 这是',
    'description' => '这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/hzwhfyal_tfzz/0323_202.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427078915',
    'updatetime' => '1427079018',
  ),
  132 => 
  array (
    'id' => '132',
    'catid' => '212',
    'typeid' => '0',
    'title' => '这是标题三这是标题三这是标题三这是标题三',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0323/20150323104415317.jpg',
    'keywords' => '标题 这是',
    'description' => '这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/hzwhfyal_tfzz/0323_132.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427078789',
    'updatetime' => '1427078905',
  ),
);
?>