<?php
return array (
  213 => 
  array (
    'id' => '213',
    'catid' => '9',
    'typeid' => '0',
    'title' => 'LATTICE点阵加密技术挽救女人头顶的稀疏',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0116/20150116063650534.jpg',
    'keywords' => '点阵 头顶 女人',
    'description' => '女性脱发在医学术语上称“弥散性脱发”。由于弥散性脱发可能因为各种原因引起，而不同于“遗传性脱发”，因此必须要由经验丰富的临床医生进行诊断。更重要的是，她们必须知道何时体检是最恰当的，植发手术对她而言是最好的选择。与典型的男性脱发相比，女性多是弥漫、稀薄的头发。与男性脱发一开始会失去大量的发迹线的头发不同，女性一般可以维持发迹线。女性脱发一般是逐渐的，但是在怀孕和绝经期会加速。女性比男性更容易发生季节性的脱发，而且更容易激素、药物和外',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/tfzz/0115_213.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421304212',
    'updatetime' => '1421470744',
  ),
  212 => 
  array (
    'id' => '212',
    'catid' => '9',
    'typeid' => '0',
    'title' => 'M型秃发际线高的原因以及如何治疗',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0109/20150109015822172.jpg',
    'keywords' => '发际 原因',
    'description' => 'M型秃顶主要是由于前额发际线植发区的皮肤，存在着微丝血管网络不丰富，血流量较慢，发根所吸收的营养较少而造成的。随着年龄的增长，雄性激素分泌增多，男性脱发更为严重，长此以往就会出现发际线后退的M秃症状。
植发是应用显微外科技术取出后枕部的健康毛囊组织，经过仔细加工培养后按照自然的头发生长方向艺术化地移植于M型秃部位，移植后的毛发能够重新生长新发，并且不会像M型脱发部头发再次坏死脱落。在无痕植发手术后，植发部位头发保持后枕部头发特性，不会再次',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/tfzz/0115_212.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421304489',
    'updatetime' => '1421470888',
  ),
  22 => 
  array (
    'id' => '22',
    'catid' => '9',
    'typeid' => '0',
    'title' => '进行植发手术请勿选择整形医院',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0109/20150109020146315.jpg',
    'keywords' => '医院',
    'description' => '目前植信一家正规植发医院就已经有近万数发友通过植发成功摆脱脱发烦恼。可见，对于很多发友来说，唯有植发才是有效的治疗脱发的方法。但发   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/tfzz/0109_22.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1420792696',
    'updatetime' => '1421470985',
  ),
  211 => 
  array (
    'id' => '211',
    'catid' => '9',
    'typeid' => '0',
    'title' => '你依然在为了面子而戴假发吗?',
    'style' => '',
    'thumb' => '',
    'keywords' => '假发 面子',
    'description' => '头发越来越少，有的地方都露出了头皮，有的人怕别人知道，碍于面子，就会选择戴假发。戴假发一来花费不大；二来能够做到以假乱真的效果；三来可以随意改变发型。对此，雍禾植发专家却表示，发友们因为头发稀疏而戴假发，是一种逃避现实的办法，因为戴假发既不能真正的解决头发稀疏的问题，而且还有可能加重脱发。因为采用先进的植发技术进行头发加密手术，这样能够避免对原生发的损伤，还能使头发更为密集，并且长出的头发永久不会脱落，和正常的头发没有任何差别。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/tfzz/0115_211.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421304693',
    'updatetime' => '1421471068',
  ),
  210 => 
  array (
    'id' => '210',
    'catid' => '9',
    'typeid' => '0',
    'title' => '亲，你该植发了',
    'style' => '',
    'thumb' => '',
    'keywords' => '亲，你该植发了',
    'description' => '脱发的严重程度分为7期，通常超过第3期以上前额部分脱发就相当明显。现有的非外科疗法一般在使用半年以后才会有效果，对头顶秃发约8成的使用者不再有异常掉发，但对前额脱发没有明显的效果。口服保发止一般在服用四个月左右，头顶脱发开始出现效果(达到8成)，但对前额脱发的效果也比较差(只有3成多)，因此前额脱发常需要配合植发来解决。如果毛囊已经坏死，不再长发，用药是不会让毛囊重新“活”起来的，只有靠植发手术来挽救啦!将自身后枕部不易脱落的头发的毛囊移植到需要',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/tfzz/0115_210.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421306412',
    'updatetime' => '1421471160',
  ),
  209 => 
  array (
    'id' => '209',
    'catid' => '9',
    'typeid' => '0',
    'title' => '三种常见的女性脱发类型',
    'style' => '',
    'thumb' => '',
    'keywords' => '常见 类型 女性',
    'description' => '女性脱发近几年来有所增长，并呈现着越来越多的趋势。但女性脱发秃露的形态大多与男性不同，脱落的原因也较为复杂，女性脱发与体内激素的分泌有着密切的关系，因而女性脱发也呈渐进型趋势，但怀孕和闭经期时会加速，而且脱发周期性强，受荷尔蒙的分泌以及外部因素的影响也比较大。某些特殊发式的机械性脱发，如辫子、发鬓等发式都会造成脱发。头发需保持一定程度的自然蓬松及适当的弹性，否则就会折断或脱落。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/tfzz/0115_209.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421306494',
    'updatetime' => '1421471236',
  ),
  208 => 
  array (
    'id' => '208',
    'catid' => '9',
    'typeid' => '0',
    'title' => '头发加密手术的原理具体是什么',
    'style' => '',
    'thumb' => '',
    'keywords' => '原理',
    'description' => '有些人的头发天生就比较少，后天再不注意合理的饮食和足够的休息时间，会使本来就少的头发越来越少的。这类人群在你进行头发加密手术的时候   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/tfzz/0115_208.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421307074',
    'updatetime' => '1421471386',
  ),
  207 => 
  array (
    'id' => '207',
    'catid' => '9',
    'typeid' => '0',
    'title' => 'LATTICE点阵加密技术有哪些特点',
    'style' => '',
    'thumb' => '',
    'keywords' => '点阵 特点 技术',
    'description' => '自古以来，女为悦己者容。而头发稀少的话，给大家的美丽也有一定的影响的。现在，治疗头发稀少最好的方法就是进行头发加密手术，但是这种手   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/tfzz/0115_207.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421307501',
    'updatetime' => '1421471512',
  ),
);
?>