<?php
return array (
  306 => 
  array (
    'id' => '306',
    'catid' => '50',
    'typeid' => '0',
    'title' => '专家全面解析植发价格中的陷阱',
    'style' => '',
    'thumb' => '',
    'keywords' => '陷阱 专家 价格',
    'description' => '导读：其实在我们生活中经常会被商家给出的价格而吸引，过低的价格总是被人关注的，可是低价格的背后是什么呢?是陷阱，那植发价格中的陷阱   ',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/fygz/0126_306.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1422251159',
    'updatetime' => '1422251201',
  ),
  305 => 
  array (
    'id' => '305',
    'catid' => '50',
    'typeid' => '0',
    'title' => '治疗脱发植发手术还是药物治疗',
    'style' => '',
    'thumb' => '',
    'keywords' => '药物 还是',
    'description' => '日常生活中很多人都面临着脱发困扰，尤其是近年来女性朋友脱发现象越来越严重，这主要和她们经常做发型和染发、烫发有关系。很多人出现脱发   ',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/fygz/0126_305.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1422250928',
    'updatetime' => '1422251099',
  ),
  304 => 
  array (
    'id' => '304',
    'catid' => '50',
    'typeid' => '0',
    'title' => '植发效果如何？从真实的案例看植发效果',
    'style' => '',
    'thumb' => '',
    'keywords' => '效果 案例',
    'description' => '随着植发技术的不断宣传和脱发人群对于脱发解决方案的效果要求不断提升，植发的效果如何也越来越受到脱发患者的关注！虽然在这个广告途径纷   ',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/fygz/0126_304.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1422250897',
    'updatetime' => '1422250919',
  ),
  303 => 
  array (
    'id' => '303',
    'catid' => '50',
    'typeid' => '0',
    'title' => '植发术后要多少时间才能看到效果',
    'style' => '',
    'thumb' => '',
    'keywords' => '效果 时间',
    'description' => '目前医学界普遍认为植发是治疗脱发最快最直接的方法，因此有许多人都通过植发来解决脱发这个大问题。但是，许多人会担心说植发之后需要多久   ',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/fygz/0126_303.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1422250867',
    'updatetime' => '1422250888',
  ),
);
?>