<?php
return array (
  281 => 
  array (
    'id' => '281',
    'catid' => '221',
    'typeid' => '0',
    'title' => '这是标题五这是标题五这是标题五这是标题五这是标题五',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0323/20150323104236122.jpg',
    'keywords' => '标题 这是',
    'description' => '这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五这是标题五',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/hzfyal_nxzf/0323_281.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427079029',
    'updatetime' => '1427079132',
  ),
  211 => 
  array (
    'id' => '211',
    'catid' => '221',
    'typeid' => '0',
    'title' => '这是标题四这是标题四这是标题四这是标题四',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0323/20150323104248597.jpg',
    'keywords' => '标题 这是',
    'description' => '这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四这是标题四',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/hzfyal_nxzf/0323_211.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427078915',
    'updatetime' => '1427079018',
  ),
  141 => 
  array (
    'id' => '141',
    'catid' => '221',
    'typeid' => '0',
    'title' => '这是标题三这是标题三这是标题三这是标题三',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0323/20150323104415317.jpg',
    'keywords' => '标题 这是',
    'description' => '这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三这是标题三',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/hzfyal_nxzf/0323_141.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427078789',
    'updatetime' => '1427078905',
  ),
  71 => 
  array (
    'id' => '71',
    'catid' => '221',
    'typeid' => '0',
    'title' => '这是标题二这是标题二这是标题二这是标题二',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0323/20150323104415317.jpg',
    'keywords' => '标题 这是',
    'description' => '这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二这是标题二',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/hzfyal_nxzf/0323_71.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1427078592',
    'updatetime' => '1427078734',
  ),
);
?>