<?php
return array (
  432 => 
  array (
    'id' => '432',
    'catid' => '91',
    'typeid' => '0',
    'title' => '植发手术其实很轻松',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0309/20150309015236257.jpg',
    'keywords' => '植发',
    'description' => '我的脱发比较严重，是斑秃。开始我以为我的头发没救了，但我还是抱着试试的态度向雍禾植发专家咨询了一下，专家说，像我这种情况可以采用毛发移植手术。并向我认真详细的说了整个过程，最后我决定接受手术。整个手术很轻松，我可以看杂志，聊天等。四个小时候，手术做完了。我照了一下镜子，斑秃的地方都种上了秘密的头发，过了三个月后，我发现我的新头发长出来了，我好激动。现在我又重新拥有了浓密的长头发，特别感谢您们，雍禾植发！',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zbbf/0309_432.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1425880336',
    'updatetime' => '1425883568',
  ),
  441 => 
  array (
    'id' => '441',
    'catid' => '91',
    'typeid' => '0',
    'title' => '天生大脑门可以解决的',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0309/20150309020250526.jpg',
    'keywords' => '脑门',
    'description' => '我是2013年10月份在北京雍禾做的发际线调整手术，距离现在已经有八个月时间了。首先我本人并不是脱发，而是天生的发际线过高，赤裸裸的大脑门令我苦恼。我是一个爱美的人，生活中的自己也经常追求完美，对于这个大脑门我不甘心总是通过留刘海来遮盖它，网上有句话说，敢留寸头的男生才是最帅的，所以我也不甘总是一种发型。
有一天在微博上看到北京雍禾可以植发，可以调整发际线，真是感叹于医疗的先进，连天生大脑门都可以解决。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zbbf/0309_441.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1425880941',
    'updatetime' => '1426656798',
  ),
  440 => 
  array (
    'id' => '440',
    'catid' => '91',
    'typeid' => '0',
    'title' => '发际线自然头发浓密',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0309/20150309020205440.jpg',
    'keywords' => '发际 头发 自然',
    'description' => '非常感谢雍禾植发医生给我做了植发手术，现在是术后1年，自然的发际线和一头浓密的头发，和1年前的我完全判若两人，老实讲刚刚做完手术我也没有想到效果会这么好，术后一个月脱发期，移植的头发开始脱落，很担心的，现在头发一天比一天多，好开心呀，感谢雍禾的植发医生们！',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zbbf/0309_440.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1425880902',
    'updatetime' => '1426656851',
  ),
  439 => 
  array (
    'id' => '439',
    'catid' => '91',
    'typeid' => '0',
    'title' => '我的疤痕上长出头发了',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0309/20150309020117177.jpg',
    'keywords' => '长出 头发 疤痕',
    'description' => '我是高中学生，小时候头皮有一块疤痕性秃发区，使我非常自卑，总是留长头发遮盖我的疤痕，在高二的时候我妈妈带我找到王永医生，在王医生那做的手术，现在是术后一年，我的疤痕上已经长出头发，完全看不出疤痕了，我的学习成绩也上升了，恢复了自信，感谢雍禾的医生，祝您们新年快乐！',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zbbf/0309_439.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1425880836',
    'updatetime' => '1426656862',
  ),
  438 => 
  array (
    'id' => '438',
    'catid' => '91',
    'typeid' => '0',
    'title' => '完全看不出是移植的眉毛',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0309/20150309015905345.jpg',
    'keywords' => '眉毛',
    'description' => '我的眉毛先天性稀疏，几乎忽略不计，纹绣过，不自然，又洗眉了，最后选择植眉，原本非常忐忑，找到了雍禾植发专家，在规定的手术日，雍禾专家非常耐心的帮助我术前设计，然后是打麻药，有点小痛，可以忍受的，整个手术时间比较长，大概是5小时，术后照镜子的时候，我非常满意，雍禾的专家很有耐心，这么长时间的手术，一直低头给我认真植眉，太值得敬佩了，手术做得太好了，给我漂亮的眉毛，完全看不出是移植的眉毛，非常自然，感觉整个人都更加有气质了，有自信了。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zbbf/0309_438.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1425880722',
    'updatetime' => '1426656883',
  ),
  437 => 
  array (
    'id' => '437',
    'catid' => '91',
    'typeid' => '0',
    'title' => '我的眉毛种植很成功',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0309/20150309015824966.jpg',
    'keywords' => '眉毛',
    'description' => '因为外伤我的眉毛少了一只，画的眉毛感觉没有立体感和另一个不对称，老觉得有点别扭，后来经过打听，知道雍禾植发做毛发移植的眉毛做得很棒。在了解手术的相关情况后做了手术，手术进行的很顺利，不到两小时就做完了，主要是眉毛打麻药痛点，后脑勺打麻药还好……现在做完手术有1年了，眉毛种植是很成功的，对现在的眉形很满意的，感谢雍禾植发。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zbbf/0309_437.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1425880686',
    'updatetime' => '1426656914',
  ),
  436 => 
  array (
    'id' => '436',
    'catid' => '91',
    'typeid' => '0',
    'title' => '雍禾植发实在靠谱',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0309/20150309015756950.jpg',
    'keywords' => '禾植发',
    'description' => '小时候烫伤留下的疤痕，找了很多大夫和医院都不太放心，我的朋友给我介绍说雍禾植发不错，他的同学就是在那里种眉毛的。我就在网络上做了预约 ，2012年8月15日，上午11 30分至下午5时，在北京雍禾植发做了头顶（烧伤秃顶）的FUE-APL2 0无痕植发技术。手术是头部局麻，手术中医生的态度和蔼，技术精湛，一直和我交谈，除了听见轻微刺头皮的声音以外，基本没有什么痛苦。手术后我就回家了。两个月开始长新发，6个月后移植的毛发生长茂盛，效果很好，雍禾植发实在靠谱，我非常满意！谢谢雍禾植发的医生们！',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zbbf/0309_436.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1425880653',
    'updatetime' => '1426656964',
  ),
  435 => 
  array (
    'id' => '435',
    'catid' => '91',
    'typeid' => '0',
    'title' => '雍禾植发，植发不再挨刀',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0309/20150309015712740.jpg',
    'keywords' => '植发 禾植发',
    'description' => '第一次做头发加密找到了雍禾植发，用的fut种植方法，手术脑后竟然出现两道很宽的疤痕，头发稍短一些疤痕非常明显，很多年我都对这个医院很抵触。幸好几年后找到了北京雍禾植发，他们采用先进的FUE-APL2 0无痕植发技术，在疤痕上种植头发，现在效果良好，感谢雍禾植发的精湛医术，让我植发不再挨刀，谢谢雍禾植发。',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zbbf/0309_435.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1425880607',
    'updatetime' => '1426657000',
  ),
);
?>