<?php
return array (
  394 => 
  array (
    'id' => '394',
    'catid' => '98',
    'typeid' => '0',
    'title' => '患者心声经典案例标题一',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011418528.jpg',
    'keywords' => '经典案例 心声 患者',
    'description' => '患者心声经典案例标题一患者心声经典案例标题一患者心声经典案例标题一患者心声经典案例标题一患者心声经典案例标题一患者心声经典案例标题一患者心声经典案例标题一患者心声经典案例标题一患者心声经典案例标题一患者心声经典案例标题一患者心声经典案例标题一患者心声经典案例标题一',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/hzxsjdal/0304_394.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425456425',
    'updatetime' => '1425456450',
  ),
  395 => 
  array (
    'id' => '395',
    'catid' => '98',
    'typeid' => '0',
    'title' => '患者心声经典案例标题二患者心声经典案例标题二',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011355366.jpg',
    'keywords' => '经典案例 心声 患者',
    'description' => '患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/hzxsjdal/0304_395.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425456455',
    'updatetime' => '1425456481',
  ),
  397 => 
  array (
    'id' => '397',
    'catid' => '98',
    'typeid' => '0',
    'title' => '患者心声经典案例标题二患者心声经典案例标题二',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011355366.jpg',
    'keywords' => '经典案例 心声 患者',
    'description' => '患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/hzxsjdal/0304_397.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425456455',
    'updatetime' => '1425456481',
  ),
  398 => 
  array (
    'id' => '398',
    'catid' => '98',
    'typeid' => '0',
    'title' => '患者心声经典案例标题三患者心声经典案例标题三',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011345968.jpg',
    'keywords' => '经典案例 心声 患者',
    'description' => '患者心声经典案例标题三患者心声经典案例标题三患者心声经典案例标题三患者心声经典案例标题三患者心声经典案例标题三患者心声经典案例标题三患者心声经典案例标题三患者心声经典案例标题三患者心声经典案例标题三患者心声经典案例标题三患者心声经典案例标题三患者心声经典案例标题三患者心声经典案例标题三患者心声经典案例标题三患者心声经典案例标题三患者心声经典案例标题三患者心声经典案例标题三患者心声经典案例标题三患者心声经典案例标题三患者心声经典案例标',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/hzxsjdal/0304_398.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425456486',
    'updatetime' => '1425456505',
  ),
  399 => 
  array (
    'id' => '399',
    'catid' => '98',
    'typeid' => '0',
    'title' => '患者心声经典案例标题四患者心声经典案例标题四',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011535352.jpg',
    'keywords' => '经典案例 心声 患者',
    'description' => '患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/hzxsjdal/0304_399.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425456511',
    'updatetime' => '1425456539',
  ),
  400 => 
  array (
    'id' => '400',
    'catid' => '98',
    'typeid' => '0',
    'title' => '患者心声经典案例标题四患者心声经典案例标题四',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011535352.jpg',
    'keywords' => '经典案例 心声 患者',
    'description' => '患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/hzxsjdal/0304_400.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425456511',
    'updatetime' => '1425456539',
  ),
  404 => 
  array (
    'id' => '404',
    'catid' => '98',
    'typeid' => '0',
    'title' => '患者心声经典案例标题五患者心声经典案例标题五',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011355366.jpg',
    'keywords' => '经典案例 心声 患者',
    'description' => '患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/hzxsjdal/0304_404.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425456553',
    'updatetime' => '1425456580',
  ),
  406 => 
  array (
    'id' => '406',
    'catid' => '98',
    'typeid' => '0',
    'title' => '患者sds心声经典案例标题六患者心声经典案例标题六患者心',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011345968.jpg',
    'keywords' => '经典案例 心声 患者',
    'description' => '患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六sdfsd',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/hzxsjdal/0304_406.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425456585',
    'updatetime' => '1425457189',
  ),
);
?>