<?php
return array (
  491 => 
  array (
    'id' => '491',
    'catid' => '98',
    'typeid' => '0',
    'title' => '是美人怎能少了美人尖',
    'style' => '',
    'thumb' => '',
    'keywords' => '美人',
    'description' => '　　最先知道女士美人尖这词是缘于一位大学同学，撸上她的留海长发，便能看见额上中部头发尖尖地突出，真如鸟喙。我的这位同学亦的确长得美   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/hzxsjdal/0318_491.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426666058',
    'updatetime' => '1426666154',
  ),
  492 => 
  array (
    'id' => '492',
    'catid' => '98',
    'typeid' => '0',
    'title' => '事业受阻，我该怎么办？',
    'style' => '',
    'thumb' => '',
    'keywords' => '怎么办 事业',
    'description' => '　　我今年27岁，刚刚大学毕业不到两年，在校时是一名优秀的学生，毕业后便顺利的进入一家知名度很高的大企业工作。但是工作期间却面临诸多   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/hzxsjdal/0318_492.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426666224',
    'updatetime' => '1426666276',
  ),
  493 => 
  array (
    'id' => '493',
    'catid' => '98',
    'typeid' => '0',
    'title' => '谢顶的恐惧叩开植发的大门',
    'style' => '',
    'thumb' => '',
    'keywords' => '植发 大门',
    'description' => '　　自从上海师范大学毕业后我就回到贵阳一所学校教书，深得学生们的喜欢与支持。然而自己心中有件事却开心不起来，因为在第二个学期的期末   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/hzxsjdal/0318_493.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426666282',
    'updatetime' => '1426666328',
  ),
  494 => 
  array (
    'id' => '494',
    'catid' => '98',
    'typeid' => '0',
    'title' => '每天都在掉发，让我情何以堪？',
    'style' => '',
    'thumb' => '',
    'keywords' => '天都',
    'description' => '　　本人今年35岁，事业刚刚稍有起色，从业务员到业务经理再到区域总监，一路走来，包含了所有的辛酸和痛苦，但如今拥有了可爱的宝贝儿子和   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/hzxsjdal/0318_494.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426666355',
    'updatetime' => '1426666390',
  ),
  495 => 
  array (
    'id' => '495',
    'catid' => '98',
    'typeid' => '0',
    'title' => '不敢梳马尾的真实原因',
    'style' => '',
    'thumb' => '',
    'keywords' => '马尾 原因',
    'description' => '　　上海的刘女士在当地一家星级酒店担任大堂经理，自从懂得辨别美丑之后，她从未扎过辫子，不管留短发还是留长发，她都喜欢用长长的刘海挡   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/hzxsjdal/0318_495.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426666417',
    'updatetime' => '1426666456',
  ),
);
?>