<?php
return array (
  173 => 
  array (
    'id' => '173',
    'catid' => '6',
    'typeid' => '0',
    'title' => '雍禾植发三场公益活动',
    'style' => '',
    'thumb' => '',
    'keywords' => '公益活动',
    'description' => '明天是7月1日，对北方的人来说，现在正值三夏时节：夏收、夏种和夏管。不过也有人这么理解三夏：初夏、中夏和盛夏，或孟夏、仲夏和季夏。作   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zxbd/0116_173.html',
    'listorder' => '1',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421387792',
    'updatetime' => '1423012683',
  ),
  172 => 
  array (
    'id' => '172',
    'catid' => '6',
    'typeid' => '0',
    'title' => '热烈祝贺雍禾植发被授予“爱心医院”',
    'style' => '',
    'thumb' => '',
    'keywords' => '爱心 医院',
    'description' => '日前，湖北省慈善总会授予雍禾植发慈善公益宝爱心医院，并颁发证书和牌匾，雍禾植发全国分院通用。　　公益宝是湖北省慈善总会打造的消费捐   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zxbd/0116_172.html',
    'listorder' => '1',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421387708',
    'updatetime' => '1423012693',
  ),
  171 => 
  array (
    'id' => '171',
    'catid' => '6',
    'typeid' => '0',
    'title' => '中国脱发人群呈年轻化诞首部植发技术标准',
    'style' => '',
    'thumb' => '',
    'keywords' => '技术标准 中国 人群',
    'description' => '内容摘要:出席中国植发行业首部质量管理体系启动仪式的皮科专家今天说，中国男性脱发人群趋向年轻化，临床发现有患者不到18岁，京沪两市30   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zxbd/0116_171.html',
    'listorder' => '1',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421387467',
    'updatetime' => '1423012703',
  ),
  170 => 
  array (
    'id' => '170',
    'catid' => '6',
    'typeid' => '0',
    'title' => '植发医院重金打造毛囊干细胞移植实验室',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0116/20150116015049911.jpg',
    'keywords' => '毛囊 干细胞 重金',
    'description' => '日前，中国植发行业的老字号植发医院雍禾植发总耗资上千万的雍禾植发毛囊干细胞移植实验室正式成立。该实验室是国内第一家致力于毛囊干细胞   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zxbd/0116_170.html',
    'listorder' => '1',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421387389',
    'updatetime' => '1423012713',
  ),
);
?>