<?php
return array (
  174 => 
  array (
    'id' => '174',
    'catid' => '49',
    'typeid' => '0',
    'title' => '第一争议：“血浆注射增发”的是与非',
    'style' => '',
    'thumb' => '',
    'keywords' => '血浆',
    'description' => '从自己身上抽取少量血液，大概是平时献血量的20分之1，经过分离提取富血小板血浆，再注射到头部脱发部位，刺激毛囊生长利于增发。这是国内   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/rdht/0116_174.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421388089',
    'updatetime' => '1421388138',
  ),
  175 => 
  array (
    'id' => '175',
    'catid' => '49',
    'typeid' => '0',
    'title' => '法制宣传日：警惕治脱发植发的非法陷阱',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '今天是12月4日，是一年一度的全国法制宣传日，也是中国第一个国家宪法日。无论是法制还是法治，都是一个宏大的课题，下含各行各业的法律法   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/rdht/0116_175.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421388292',
    'updatetime' => '1421388448',
  ),
  177 => 
  array (
    'id' => '177',
    'catid' => '49',
    'typeid' => '0',
    'title' => '你可曾这样“药药相加”地垒天梯？很危险啊！',
    'style' => '',
    'thumb' => '',
    'keywords' => '天梯',
    'description' => '雍禾不给患者搭售防脱药，但也强调植发和药物的辩证施治，而一些同行给患者搭售药物也强调植发和药物的辩证施治。这就让发友们听了迷惑，两   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/rdht/0116_177.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421388932',
    'updatetime' => '1421389004',
  ),
  179 => 
  array (
    'id' => '179',
    'catid' => '49',
    'typeid' => '0',
    'title' => '中国医师道德准则发布，植发业对号入座',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0116/20150116022224745.jpg',
    'keywords' => '中国 医师 准则',
    'description' => '昨天(6月25日)，中国医师协会发布了中国医师道德准则，以规范医师的道德底线，促使医师把职业谋生手段升华为职业信仰。全文共分基本准则、   ',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/rdht/0116_179.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421389329',
    'updatetime' => '1421391990',
  ),
  178 => 
  array (
    'id' => '178',
    'catid' => '49',
    'typeid' => '0',
    'title' => '雍禾评论：让诚信成为植发业的主基调',
    'style' => '',
    'thumb' => '',
    'keywords' => '基调',
    'description' => '　　2014年5月，雍禾植发推出五大保障，其内容包括：确保医生亲诊，确保毛囊成活率95%，确保预约金订的优惠手术长期有效，确保不过度医疗不   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/rdht/0116_178.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421389237',
    'updatetime' => '1421734204',
  ),
  176 => 
  array (
    'id' => '176',
    'catid' => '49',
    'typeid' => '0',
    'title' => '怪象！植发技术争不了，药物搭售来助阵',
    'style' => '',
    'thumb' => '',
    'keywords' => '怪象 药物 技术',
    'description' => '(治秃顶的天平：植发相当于石头，分量最重；鸡毛相当于药物，分量最轻。)　　最近两年，中国植发界有一股逆流，就是过度医疗，典型的是搭售   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/rdht/0116_176.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421388576',
    'updatetime' => '1421734225',
  ),
);
?>