<?php
return array (
  412 => 
  array (
    'id' => '412',
    'catid' => '102',
    'typeid' => '0',
    'title' => '标题一标题一标题一标题一标题一标题一标题一',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0310/20150310043217339.jpg',
    'keywords' => '标题',
    'description' => '标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一标题一',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/fygw/0310_412.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425976289',
    'updatetime' => '1425976356',
  ),
  416 => 
  array (
    'id' => '416',
    'catid' => '102',
    'typeid' => '0',
    'title' => '标题三标题三标题三标题三标题三标题三标题三标题三标题',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0310/20150310043347593.jpg',
    'keywords' => '标题',
    'description' => '标题三标题三标题三标题三标题三标题三标题三标题三标题三标题三标题三标题三标题三标题三标题三标题三标题三标题三标题三标题三标题三',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/fygw/0310_416.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425976397',
    'updatetime' => '1425976430',
  ),
  419 => 
  array (
    'id' => '419',
    'catid' => '102',
    'typeid' => '0',
    'title' => '标题四标题四标题四标题四标题四标题四',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0310/20150310043426320.jpg',
    'keywords' => '标题',
    'description' => '标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四标题四',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/fygw/0310_419.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425976436',
    'updatetime' => '1425976470',
  ),
  424 => 
  array (
    'id' => '424',
    'catid' => '102',
    'typeid' => '0',
    'title' => '标题六标题六标题六标题六标题六标题六',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0310/20150310043310824.jpg',
    'keywords' => '标题',
    'description' => '标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六标题六',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/fygw/0310_424.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425976519',
    'updatetime' => '1425976548',
  ),
  428 => 
  array (
    'id' => '428',
    'catid' => '102',
    'typeid' => '0',
    'title' => '标题七标题七标题七',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0310/20150310043217339.jpg',
    'keywords' => '标题',
    'description' => '标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七标题七',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/fygw/0310_428.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425976552',
    'updatetime' => '1425976579',
  ),
);
?>