<?php
return array (
  487 => 
  array (
    'id' => '487',
    'catid' => '102',
    'typeid' => '0',
    'title' => '是美人怎能少了美人尖',
    'style' => '',
    'thumb' => '',
    'keywords' => '美人',
    'description' => '　　最先知道女士美人尖这词是缘于一位大学同学，撸上她的留海长发，便能看见额上中部头发尖尖地突出，真如鸟喙。我的这位同学亦的确长得美   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/fygw/0318_487.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426665582',
    'updatetime' => '1426665630',
  ),
  488 => 
  array (
    'id' => '488',
    'catid' => '102',
    'typeid' => '0',
    'title' => '事业受阻，我该怎么办？',
    'style' => '',
    'thumb' => '',
    'keywords' => '怎么办 事业',
    'description' => '　　我今年27岁，刚刚大学毕业不到两年，在校时是一名优秀的学生，毕业后便顺利的进入一家知名度很高的大企业工作。但是工作期间却面临诸多   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/fygw/0318_488.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426665676',
    'updatetime' => '1426665775',
  ),
  489 => 
  array (
    'id' => '489',
    'catid' => '102',
    'typeid' => '0',
    'title' => '谢顶的恐惧叩开植发的大门',
    'style' => '',
    'thumb' => '',
    'keywords' => '植发 大门',
    'description' => '自从上海师范大学毕业后我就回到贵阳一所学校教书，深得学生们的喜欢与支持。然而自己心中有件事却开心不起来，因为在第二个学期的期末考试   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/fygw/0318_489.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426665825',
    'updatetime' => '1426665877',
  ),
  490 => 
  array (
    'id' => '490',
    'catid' => '102',
    'typeid' => '0',
    'title' => '每天都在掉发，让我情何以堪？',
    'style' => '',
    'thumb' => '',
    'keywords' => '天都',
    'description' => '　　本人今年35岁，事业刚刚稍有起色，从业务员到业务经理再到区域总监，一路走来，包含了所有的辛酸和痛苦，但如今拥有了可爱的宝贝儿子和   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/fygw/0318_490.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426665899',
    'updatetime' => '1426665943',
  ),
);
?>