<?php
return array (
  73 => 
  array (
    'id' => '73',
    'content' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="http://player.ku6.com/refer/WigOmMBcp8wuXnrzvmOjGg../v.swf" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="http://player.ku6.com/refer/WigOmMBcp8wuXnrzvmOjGg../v.swf" type="application/x-shockwave-flash"></embed></object>',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0" height="400" width="700"><param name="quality" value="high" /><param name="movie" value="http://www.tudou.com/v/GJvvMH_58u8/&amp;resourceId=0_04_05_99/v.swf" /><embed height="400" pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="http://www.tudou.com/v/GJvvMH_58u8/&amp;resourceId=0_04_05_99/v.swf" type="application/x-shockwave-flash" width="700"></embed></object>',
    'catid' => '60',
    'typeid' => '0',
    'title' => '首部植发质量管理体系出台',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0122/20150122025031379.jpg',
    'keywords' => '管理体系 质量',
    'description' => '首部植发质量管理体系出台
',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/yhalsp/0122_73.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421906186',
    'updatetime' => '1423186104',
  ),
  74 => 
  array (
    'id' => '74',
    'content' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=61168320&amp;autoplay=false&amp;from=page" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=61168320&amp;autoplay=false&amp;from=page" type="application/x-shockwave-flash"></embed></object>',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0" height="400" width="700"><param name="quality" value="high" /><param name="movie" value="http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=61168320&amp;autoplay=false&amp;from=page" /><embed height="400" pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=61168320&amp;autoplay=false&amp;from=page" type="application/x-shockwave-flash" width="700"></embed></object>',
    'catid' => '60',
    'typeid' => '0',
    'title' => '患者韩国考察回来发布会 韩国和中国植发技术对比',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0122/20150122025010490.jpg',
    'keywords' => '韩国 中国 发布会',
    'description' => '患者韩国考察回来发布会 韩国和中国植发技术对比
',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/yhalsp/0122_74.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421906212',
    'updatetime' => '1423185705',
  ),
  75 => 
  array (
    'id' => '75',
    'content' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=61168320&amp;autoplay=false&amp;from=page" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="http://share.vrs.sohu.com/my/v.swf&amp;topBar=1&amp;id=61168320&amp;autoplay=false&amp;from=page" type="application/x-shockwave-flash"></embed></object>',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0" height="400" width="700"><param name="quality" value="high" /><param name="movie" value="http://player.youku.com/player.php/sid/XMjkzMzIxMDc2/v.swf" /><embed height="400" pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="http://player.youku.com/player.php/sid/XMjkzMzIxMDc2/v.swf" type="application/x-shockwave-flash" width="700"></embed></object>',
    'catid' => '60',
    'typeid' => '0',
    'title' => '雍禾植发公益互动',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0122/20150122024811171.jpg',
    'keywords' => '公益',
    'description' => '雍禾植发公益互动
',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/yhalsp/0122_75.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421906247',
    'updatetime' => '1423185634',
  ),
  72 => 
  array (
    'id' => '72',
    'content' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"><param name="quality" value="high" /><param name="movie" value="http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" /><embed pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" type="application/x-shockwave-flash"></embed></object>',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
    'shipin' => '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0" height="400" width="700"><param name="quality" value="high" /><param name="movie" value="http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" /><embed height="400" pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="http://static.video.qq.com/TPout.swf?vid=o10826q3mmn&amp;auto=0" type="application/x-shockwave-flash" width="700"></embed></object>',
    'catid' => '60',
    'typeid' => '0',
    'title' => '《都市新闻眼》报道雍禾植发透明植发理念',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0122/20150122025153263.jpg',
    'keywords' => '理念 都市 新闻',
    'description' => '《都市新闻眼》报道雍禾植发透明植发理念
',
    'posids' => '1',
    'url' => 'http://www.bjshenniao.cn/yhalsp/0122_72.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421906009',
    'updatetime' => '1423185481',
  ),
);
?>