<?php
return array (
  335 => 
  array (
    'id' => '335',
    'catid' => '70',
    'typeid' => '0',
    'title' => '植发技术有多少种，哪个好？',
    'style' => '',
    'thumb' => '',
    'keywords' => '技术',
    'description' => '当众多脱发患者经过生发药、中药调理、传统偏方等五花八门、琳琅满目的生发方法后，仍不能达到理想效果之时，最终敲开了植发的大门，可是大   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/dtjsys/0205_335.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1423111244',
    'updatetime' => '1423111344',
  ),
  336 => 
  array (
    'id' => '336',
    'catid' => '70',
    'typeid' => '0',
    'title' => '部分生发剂有致癌性，真的吗？',
    'style' => '',
    'thumb' => '',
    'keywords' => '致癌性 部分',
    'description' => '脱发在我们周围较为常见，很多人可能都不以为然，殊不知脱发乃是医学常见的皮肤性疾病，虽然没有危及生命与生存，但因其严重影响患者的外观   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/dtjsys/0205_336.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1423111412',
    'updatetime' => '1423111450',
  ),
  337 => 
  array (
    'id' => '337',
    'catid' => '70',
    'typeid' => '0',
    'title' => '毛囊坏死后能用生发剂吗？',
    'style' => '',
    'thumb' => '',
    'keywords' => '毛囊',
    'description' => '毛囊坏死后能用生发剂吗？生发剂一直是脱发患者依赖的工具，很多脱发患者在刚开始脱发时都曾使用过生发剂，但是部分发友有良好效果，而大部   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/dtjsys/0205_337.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1423111479',
    'updatetime' => '1423111536',
  ),
  338 => 
  array (
    'id' => '338',
    'catid' => '70',
    'typeid' => '0',
    'title' => '我为何使用生发剂无效？',
    'style' => '',
    'thumb' => '',
    'keywords' => '我为何使用生发剂无效？',
    'description' => '为什么我的头发还是脱落，为什么我买的生发剂不管用？为什么别人用生发剂就可以，而我使用生发剂无效呢？这是很多发友常问的问题。生发剂奈   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/dtjsys/0205_338.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1423111550',
    'updatetime' => '1423111585',
  ),
  356 => 
  array (
    'id' => '356',
    'catid' => '70',
    'typeid' => '0',
    'title' => 'UHE微米级无痕植眉技术',
    'style' => '',
    'thumb' => '',
    'keywords' => '微米 技术',
    'description' => '雍禾植发国际权威专家自主研发的UHE微米级无痕植眉技术是亚洲首个专门应用于眉毛种植的技术体系。采用国际植发界最先进APL2 0高密度、高精   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/dtjsys/0206_356.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1423192079',
    'updatetime' => '1423192092',
  ),
  357 => 
  array (
    'id' => '357',
    'catid' => '70',
    'typeid' => '0',
    'title' => '国际先进无痕加密技术',
    'style' => '',
    'thumb' => '',
    'keywords' => '先进 国际 技术',
    'description' => '雍禾植发LATTICE点阵加密技术是雍禾植发技术研究院数位国际知名植发专家，在植发技术第六次改革中，根据亚洲人皮肤、毛发特征，于2010年自   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/dtjsys/0206_357.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1423192115',
    'updatetime' => '1423192124',
  ),
);
?>