<?php
return array (
  167 => 
  array (
    'id' => '167',
    'catid' => '6',
    'typeid' => '0',
    'title' => '五项保证是“法治植发”标本',
    'style' => '',
    'thumb' => '',
    'keywords' => '标本 法治',
    'description' => '明天下午，十八届四中全会闭幕，届时公报中的法治议题将是舆论关注的焦点，因为本届会议第一次将法治单独作一个议题在全会讨论。不少有识之   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zxbd/0116_167.html',
    'listorder' => '1',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421387243',
    'updatetime' => '1422238090',
  ),
  166 => 
  array (
    'id' => '166',
    'catid' => '6',
    'typeid' => '0',
    'title' => '玩转顶上魅惑，明星植发又添新贵',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0116/20150116013826835.jpg',
    'keywords' => '新贵 明星',
    'description' => '一个人是否有魅力，难掩的风姿都是从发端开始的，连接着心灵和情怀的每一根发丝都蕴涵着生命的活力。如果你的秀发过早凋零，那就绝决的对你   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zxbd/0116_166.html',
    'listorder' => '1',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421386582',
    'updatetime' => '1422238098',
  ),
  165 => 
  array (
    'id' => '165',
    'catid' => '6',
    'typeid' => '0',
    'title' => '脱发治疗药可引起性欲减退和勃起功能障碍',
    'style' => '',
    'thumb' => '',
    'keywords' => '脱发治疗 性欲减退 障碍',
    'description' => '据MDINDIA网站报道，来自波士顿大学医学院（BUSM）的研究人员与Lahey诊所以及丹麦和德国的同事合作研究发现，5a-还原酶抑制剂（5a-RIs）在   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zxbd/0116_165.html',
    'listorder' => '1',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421386513',
    'updatetime' => '1422238107',
  ),
  164 => 
  array (
    'id' => '164',
    'catid' => '6',
    'typeid' => '0',
    'title' => '秃头影响求职 脱发男性要美容',
    'style' => '',
    'thumb' => '',
    'keywords' => '秃头 男性',
    'description' => '男性脱发影响求职？听起来有点危言耸听的论调被一项最新调查不幸证实。最近由华东师范大学心理学系副教授邓赐平博士主持执行的一场调查显示   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zxbd/0116_164.html',
    'listorder' => '1',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421386421',
    'updatetime' => '1422238115',
  ),
  163 => 
  array (
    'id' => '163',
    'catid' => '6',
    'typeid' => '0',
    'title' => '头顶功夫“亮”出来',
    'style' => '',
    'thumb' => '',
    'keywords' => '头顶 功夫',
    'description' => '　　雍禾植发创新质管体系实现良性发展　　一间充满温馨的房间、墙上挂着一台电视，两个画面同时并列出现在屏幕上，放映的不是电影电视节目   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zxbd/0116_163.html',
    'listorder' => '1',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421386300',
    'updatetime' => '1422238122',
  ),
  162 => 
  array (
    'id' => '162',
    'catid' => '6',
    'typeid' => '0',
    'title' => '全球最容易脱发的五大职业',
    'style' => '',
    'thumb' => '',
    'keywords' => '职业 全球',
    'description' => '　　核心提示：国外的一项调查表明，脱发人群在年龄、性别甚至职业上都有明显的特征，这表明，一些生活在特殊环境的人更容易脱发。　　有资   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zxbd/0116_162.html',
    'listorder' => '1',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421384968',
    'updatetime' => '1422238135',
  ),
  161 => 
  array (
    'id' => '161',
    'catid' => '6',
    'typeid' => '0',
    'title' => '广州雍禾FUE-APL2.0推介会举行',
    'style' => '',
    'thumb' => '',
    'keywords' => '推介会 广州',
    'description' => '2014年11月8日，雍禾15年院庆暨FUE-APL2 0推介会在广州市天河区华金盾大酒店盛大举行，南方的150名发友前来助阵贺禧雍禾的无痕技术再升级，   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zxbd/0116_161.html',
    'listorder' => '1',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421384492',
    'updatetime' => '1422238142',
  ),
  160 => 
  array (
    'id' => '160',
    'catid' => '6',
    'typeid' => '0',
    'title' => '大众调查：秃顶带来信任危机',
    'style' => '',
    'thumb' => '',
    'keywords' => '危机',
    'description' => '随着经济危机的和金融风暴席卷全球之时，脱发危机也开始异军突起，成为脱发患者难言的隐痛。由于工作压力和环境的恶化，越来越多的人开始脱   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/zxbd/0116_160.html',
    'listorder' => '1',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421384273',
    'updatetime' => '1422238149',
  ),
);
?>