<?php
return array (
  362 => 
  array (
    'id' => '362',
    'catid' => '92',
    'typeid' => '0',
    'title' => '相亲失败N次只因秃顶标题一',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011535352.jpg',
    'keywords' => '标题',
    'description' => '相亲失败N次只因秃顶标题一相亲失败N次只因秃顶标题一相亲失败N次只因秃顶标题一相亲失败N次只因秃顶标题一相亲失败N次只因秃顶标题一相亲失败N次只因秃顶标题一相亲失败N次只因秃顶标题一相亲失败N次只因秃顶标题一相亲失败N次只因秃顶标题一相亲失败N次只因秃顶标题一相亲失败N次只因秃顶标题一相亲失败N次只因秃顶标题一相亲失败N次只因秃顶标题一相亲失败N次只因秃顶标题一',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/ybbf/0228_362.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425101729',
    'updatetime' => '1425101749',
  ),
  363 => 
  array (
    'id' => '363',
    'catid' => '92',
    'typeid' => '0',
    'title' => '相亲失败N次只因秃顶标题二',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011355366.jpg',
    'keywords' => '标题',
    'description' => '相亲失败N次只因秃顶标题二相亲失败N次只因秃顶标题二相亲失败N次只因秃顶标题二相亲失败N次只因秃顶标题二相亲失败N次只因秃顶标题二相亲失败N次只因秃顶标题二相亲失败N次只因秃顶标题二相亲失败N次只因秃顶标题二相亲失败N次只因秃顶标题二相亲失败N次只因秃顶标题二相亲失败N次只因秃顶标题二相亲失败N次只因秃顶标题二',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/ybbf/0228_363.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425101760',
    'updatetime' => '1425101778',
  ),
  364 => 
  array (
    'id' => '364',
    'catid' => '92',
    'typeid' => '0',
    'title' => '相亲失败N次只因秃顶标题三',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011355366.jpg',
    'keywords' => '标题',
    'description' => '相亲失败N次只因秃顶标题三相亲失败N次只因秃顶标题三相亲失败N次只因秃顶标题三相亲失败N次只因秃顶标题三相亲失败N次只因秃顶标题三相亲失败N次只因秃顶标题三相亲失败N次只因秃顶标题三相亲失败N次只因秃顶标题三相亲失败N次只因秃顶标题三相亲失败N次只因秃顶标题三相亲失败N次只因秃顶标题三相亲失败N次只因秃顶标题三',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/ybbf/0228_364.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425101782',
    'updatetime' => '1425101799',
  ),
  365 => 
  array (
    'id' => '365',
    'catid' => '92',
    'typeid' => '0',
    'title' => '相亲失败N次只因秃顶标题四',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011345968.jpg',
    'keywords' => '标题',
    'description' => '相亲失败N次只因秃顶标题四相亲失败N次只因秃顶标题四相亲失败N次只因秃顶标题四相亲失败N次只因秃顶标题四相亲失败N次只因秃顶标题四相亲失败N次只因秃顶标题四相亲失败N次只因秃顶标题四相亲失败N次只因秃顶标题四相亲失败N次只因秃顶标题四相亲失败N次只因秃顶标题四相亲失败N次只因秃顶标题四相亲失败N次只因秃顶标题四相亲失败N次只因秃顶标题四相亲失败N次只因秃顶标题四相亲失败N次只因秃顶标题四相亲失败N次只因秃顶标题四相亲失败N次只因秃顶标题四',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/ybbf/0228_365.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425101804',
    'updatetime' => '1425101824',
  ),
  366 => 
  array (
    'id' => '366',
    'catid' => '92',
    'typeid' => '0',
    'title' => '相亲失败N次只因秃顶标题五',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011345968.jpg',
    'keywords' => '标题',
    'description' => '相亲失败N次只因秃顶标题五相亲失败N次只因秃顶标题五相亲失败N次只因秃顶标题五相亲失败N次只因秃顶标题五相亲失败N次只因秃顶标题五相亲失败N次只因秃顶标题五相亲失败N次只因秃顶标题五相亲失败N次只因秃顶标题五相亲失败N次只因秃顶标题五相亲失败N次只因秃顶标题五相亲失败N次只因秃顶标题五相亲失败N次只因秃顶标题五相亲失败N次只因秃顶标题五相亲失败N次只因秃顶标题五相亲失败N次只因秃顶标题五',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/ybbf/0228_366.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425101848',
    'updatetime' => '1425101868',
  ),
  367 => 
  array (
    'id' => '367',
    'catid' => '92',
    'typeid' => '0',
    'title' => '相亲失败N次只因秃顶标题六',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011404328.jpg',
    'keywords' => '标题',
    'description' => '相亲失败N次只因秃顶标题六相亲失败N次只因秃顶标题六相亲失败N次只因秃顶标题六相亲失败N次只因秃顶标题六相亲失败N次只因秃顶标题六相亲失败N次只因秃顶标题六相亲失败N次只因秃顶标题六相亲失败N次只因秃顶标题六相亲失败N次只因秃顶标题六相亲失败N次只因秃顶标题六相亲失败N次只因秃顶标题六相亲失败N次只因秃顶标题六相亲失败N次只因秃顶标题六相亲失败N次只因秃顶标题六相亲失败N次只因秃顶标题六相亲失败N次只因秃顶标题六相亲失败N次只因秃顶标题六',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/ybbf/0228_367.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425101872',
    'updatetime' => '1425101889',
  ),
  368 => 
  array (
    'id' => '368',
    'catid' => '92',
    'typeid' => '0',
    'title' => '相亲失败N次只因秃顶标题七',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011535352.jpg',
    'keywords' => '标题',
    'description' => '相亲失败N次只因秃顶标题七相亲失败N次只因秃顶标题七相亲失败N次只因秃顶标题七相亲失败N次只因秃顶标题七相亲失败N次只因秃顶标题七相亲失败N次只因秃顶标题七相亲失败N次只因秃顶标题七相亲失败N次只因秃顶标题七相亲失败N次只因秃顶标题七相亲失败N次只因秃顶标题七相亲失败N次只因秃顶标题七相亲失败N次只因秃顶标题七相亲失败N次只因秃顶标题七相亲失败N次只因秃顶标题七相亲失败N次只因秃顶标题七相亲失败N次只因秃顶标题七相亲失败N次只因秃顶标题七相亲失败N次只因秃',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/ybbf/0228_368.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425101893',
    'updatetime' => '1425101912',
  ),
);
?>