<?php
return array (
  410 => 
  array (
    'id' => '410',
    'catid' => '99',
    'typeid' => '0',
    'title' => '患者心声经典案例标题七患者心声经典案例标题七患者心声',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011535352.jpg',
    'keywords' => '心声 患者 经典案例',
    'description' => '患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/xsttzjry/0304_410.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425457830',
    'updatetime' => '1425457865',
  ),
  407 => 
  array (
    'id' => '407',
    'catid' => '99',
    'typeid' => '0',
    'title' => '患者safafaffff心声经典案例标题六患者心声经典案例标题六者',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011345968.jpg',
    'keywords' => '经典案例 心声 患者',
    'description' => '患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者ssssssss心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/xsttzjry/0304_407.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425456585',
    'updatetime' => '1425457209',
  ),
  405 => 
  array (
    'id' => '405',
    'catid' => '99',
    'typeid' => '0',
    'title' => '患者心声经典案例标题六患者心声经典案例标题六',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011345968.jpg',
    'keywords' => '经典案例 心声 患者',
    'description' => '患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/xsttzjry/0304_405.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425456585',
    'updatetime' => '1425456614',
  ),
  402 => 
  array (
    'id' => '402',
    'catid' => '99',
    'typeid' => '0',
    'title' => '患者心声经典案例标题五患者心声经典案例标题五',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011355366.jpg',
    'keywords' => '经典案例 心声 患者',
    'description' => '患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/xsttzjry/0304_402.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425456553',
    'updatetime' => '1425456580',
  ),
  403 => 
  array (
    'id' => '403',
    'catid' => '99',
    'typeid' => '0',
    'title' => '患者心声经典案例标题五患者心声经典案例标题五',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011355366.jpg',
    'keywords' => '经典案例 心声 患者',
    'description' => '患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/xsttzjry/0304_403.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425456553',
    'updatetime' => '1425456580',
  ),
  401 => 
  array (
    'id' => '401',
    'catid' => '99',
    'typeid' => '0',
    'title' => '患者心声经典案例标题四患者心声经典案例标题四',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011535352.jpg',
    'keywords' => '经典案例 心声 患者',
    'description' => '患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/xsttzjry/0304_401.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425456511',
    'updatetime' => '1425456539',
  ),
  396 => 
  array (
    'id' => '396',
    'catid' => '99',
    'typeid' => '0',
    'title' => '患者心声经典案例标题二患者心声经典案例标题二',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011355366.jpg',
    'keywords' => '经典案例 心声 患者',
    'description' => '患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标题二患者心声经典案例标',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/xsttzjry/0304_396.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425456455',
    'updatetime' => '1425456481',
  ),
);
?>