<?php
return array (
  474 => 
  array (
    'id' => '474',
    'catid' => '99',
    'typeid' => '0',
    'title' => 'FUT与FUE植发技术全方位比较》论文引起热烈反响',
    'style' => '',
    'thumb' => '',
    'keywords' => '植发 反响 全方位',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/xsttzjry/0313_474.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426212564',
    'updatetime' => '1426212579',
  ),
  473 => 
  array (
    'id' => '473',
    'catid' => '99',
    'typeid' => '0',
    'title' => '我院植发专家获得美国整形杂志的最佳论文奖',
    'style' => '',
    'thumb' => '',
    'keywords' => '植发 美国 杂志',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/xsttzjry/0313_473.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426212533',
    'updatetime' => '1426212553',
  ),
  472 => 
  array (
    'id' => '472',
    'catid' => '99',
    'typeid' => '0',
    'title' => '2014第四届全球华裔整形外科医师大会',
    'style' => '',
    'thumb' => '',
    'keywords' => '整形外科 华裔 第四届',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/xsttzjry/0313_472.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426212514',
    'updatetime' => '1426212528',
  ),
  471 => 
  array (
    'id' => '471',
    'catid' => '99',
    'typeid' => '0',
    'title' => '第三届中国医疗整形美容行业发展高峰论坛',
    'style' => '',
    'thumb' => '',
    'keywords' => '国医 整形美容 行业发展',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/xsttzjry/0313_471.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426212494',
    'updatetime' => '1426212510',
  ),
  470 => 
  array (
    'id' => '470',
    'catid' => '99',
    'typeid' => '0',
    'title' => '第22届世界植发大会',
    'style' => '',
    'thumb' => '',
    'keywords' => '植发 大会 世界',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/xsttzjry/0313_470.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426211917',
    'updatetime' => '1426211938',
  ),
  469 => 
  array (
    'id' => '469',
    'catid' => '99',
    'typeid' => '0',
    'title' => '第13届中韩植发技术交流会在韩国举行',
    'style' => '',
    'thumb' => '',
    'keywords' => '韩国 交流会 技术',
    'description' => '日前，第13届中韩植发技术交流会在韩国JK医疗美容医院隆重召开，韩国植发医师向中国学习交流无痕植发技术这还是头一次，国内外多名植发医师   ',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/xsttzjry/0313_469.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426211889',
    'updatetime' => '1426211907',
  ),
  468 => 
  array (
    'id' => '468',
    'catid' => '99',
    'typeid' => '0',
    'title' => '2014年中韩国际整形美容学术大会',
    'style' => '',
    'thumb' => '',
    'keywords' => '整形美容 学术 大会',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/xsttzjry/0313_468.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1426211510',
    'updatetime' => '1426211574',
  ),
);
?>