<?php
return array (
  408 => 
  array (
    'id' => '408',
    'catid' => '98',
    'typeid' => '0',
    'title' => '患者心声经典案例标题七患者心声经典案例标题七患者心声',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011535352.jpg',
    'keywords' => '心声 患者 经典案例',
    'description' => '患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/hzxsjdal/0304_408.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425457830',
    'updatetime' => '1425457865',
  ),
  409 => 
  array (
    'id' => '409',
    'catid' => '98',
    'typeid' => '0',
    'title' => '患者心声经典案例标题七患者心声经典案例标题七患者心声',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011535352.jpg',
    'keywords' => '心声 患者 经典案例',
    'description' => '患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七患者心声经典案例标题七',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/hzxsjdal/0304_409.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425457830',
    'updatetime' => '1425457865',
  ),
  406 => 
  array (
    'id' => '406',
    'catid' => '98',
    'typeid' => '0',
    'title' => '患者sds心声经典案例标题六患者心声经典案例标题六患者心',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011345968.jpg',
    'keywords' => '经典案例 心声 患者',
    'description' => '患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六患者心声经典案例标题六sdfsd',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/hzxsjdal/0304_406.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425456585',
    'updatetime' => '1425457189',
  ),
  404 => 
  array (
    'id' => '404',
    'catid' => '98',
    'typeid' => '0',
    'title' => '患者心声经典案例标题五患者心声经典案例标题五',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011355366.jpg',
    'keywords' => '经典案例 心声 患者',
    'description' => '患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五患者心声经典案例标题五',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/hzxsjdal/0304_404.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425456553',
    'updatetime' => '1425456580',
  ),
  399 => 
  array (
    'id' => '399',
    'catid' => '98',
    'typeid' => '0',
    'title' => '患者心声经典案例标题四患者心声经典案例标题四',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011535352.jpg',
    'keywords' => '经典案例 心声 患者',
    'description' => '患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四患者心声经典案例标题四',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/hzxsjdal/0304_399.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425456511',
    'updatetime' => '1425456539',
  ),
);
?>