<?php
return array (
  369 => 
  array (
    'id' => '369',
    'catid' => '93',
    'typeid' => '0',
    'title' => '判断植发效果完美的四个标题一',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011509660.jpg',
    'keywords' => '植发 效果 标题',
    'description' => '判断植发效果完美的四个标题一判断植发效果完美的四个标题一判断植发效果完美的四个标题一判断植发效果完美的四个标题一判断植发效果完美的四个标题一判断植发效果完美的四个标题一判断植发效果完美的四个标题一判断植发效果完美的四个标题一判断植发效果完美的四个标题一判断植发效果完美的四个标题一',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/yhzjzg/0228_369.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425101960',
    'updatetime' => '1425101982',
  ),
  370 => 
  array (
    'id' => '370',
    'catid' => '93',
    'typeid' => '0',
    'title' => '判断植发效果完美的四个标题二',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011355366.jpg',
    'keywords' => '植发 效果 标题',
    'description' => '判断植发效果完美的四个标题二判断植发效果完美的四个标题二判断植发效果完美的四个标题二判断植发效果完美的四个标题二判断植发效果完美的四个标题二判断植发效果完美的四个标题二判断植发效果完美的四个标题二判断植发效果完美的四个标题二判断植发效果完美的四个标题二',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/yhzjzg/0228_370.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425101985',
    'updatetime' => '1425102011',
  ),
  371 => 
  array (
    'id' => '371',
    'catid' => '93',
    'typeid' => '0',
    'title' => '判断植发效果完美的四个标题三',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011509660.jpg',
    'keywords' => '植发 效果 标题',
    'description' => '判断植发效果完美的四个标题三判断植发效果完美的四个标题三判断植发效果完美的四个标题三判断植发效果完美的四个标题三判断植发效果完美的四个标题三判断植发效果完美的四个标题三判断植发效果完美的四个标题三判断植发效果完美的四个标题三判断植发效果完美的四个标题三判断植发效果完美的四个标题三',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/yhzjzg/0228_371.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425102016',
    'updatetime' => '1425102034',
  ),
  372 => 
  array (
    'id' => '372',
    'catid' => '93',
    'typeid' => '0',
    'title' => '判断植发效果完美的四个标题四',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011355366.jpg',
    'keywords' => '植发 效果 标题',
    'description' => '判断植发效果完美的四个标题四判断植发效果完美的四个标题四判断植发效果完美的四个标题四判断植发效果完美的四个标题四判断植发效果完美的四个标题四判断植发效果完美的四个标题四判断植发效果完美的四个标题四判断植发效果完美的四个标题四判断植发效果完美的四个标题四判断植发效果完美的四个标题四判断植发效果完美的四个标题四判断植发效果完美的四个标题四判断植发效果完美的四个标题四判断植发效果完美的四个标题四判断植发效果完美的四个标题四判断植发效果完美',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/yhzjzg/0228_372.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425102051',
    'updatetime' => '1425102071',
  ),
  373 => 
  array (
    'id' => '373',
    'catid' => '93',
    'typeid' => '0',
    'title' => '判断植发效果完美的四个标题五',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011345968.jpg',
    'keywords' => '植发 效果 标题',
    'description' => '判断植发效果完美的四个标题五判断植发效果完美的四个标题五判断植发效果完美的四个标题五判断植发效果完美的四个标题五判断植发效果完美的四个标题五判断植发效果完美的四个标题五判断植发效果完美的四个标题五判断植发效果完美的四个标题五判断植发效果完美的四个标题五判断植发效果完美的四个标题五判断植发效果完美的四个标题五判断植发效果完美的四个标题五判断植发效果完美的四个标题五',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/yhzjzg/0228_373.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425102075',
    'updatetime' => '1425102113',
  ),
  377 => 
  array (
    'id' => '377',
    'catid' => '93',
    'typeid' => '0',
    'title' => '判断植发效果完美的四个标题六',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011509660.jpg',
    'keywords' => '植发 效果 标题',
    'description' => '判断植发效果完美的四个标题六判断植发效果完美的四个标题六判断植发效果完美的四个标题六判断植发效果完美的四个标题六判断植发效果完美的四个标题六判断植发效果完美的四个标题六判断植发效果完美的四个标题六判断植发效果完美的四个标题六判断植发效果完美的四个标题六判断植发效果完美的四个标题六判断植发效果完美的四个标题六',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/yhzjzg/0228_377.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425102184',
    'updatetime' => '1425102212',
  ),
  381 => 
  array (
    'id' => '381',
    'catid' => '93',
    'typeid' => '0',
    'title' => '判断植发效果完美的四个标题七',
    'style' => '',
    'thumb' => 'http://www.bjshenniao.cn/uploadfile/2015/0228/20150228011355366.jpg',
    'keywords' => '植发 效果 标题',
    'description' => '判断植发效果完美的四个标题七判断植发效果完美的四个标题七判断植发效果完美的四个标题七判断植发效果完美的四个标题七判断植发效果完美的四个标题七判断植发效果完美的四个标题七判断植发效果完美的四个标题七判断植发效果完美的四个标题七判断植发效果完美的四个标题七判断植发效果完美的四个标题七判断植发效果完美的四个标题七判断植发效果完美的四个标题七',
    'posids' => '0',
    'url' => 'http://www.bjshenniao.cn/yhzjzg/0228_381.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'zhifa_cn',
    'inputtime' => '1425102224',
    'updatetime' => '1425102245',
  ),
);
?>