<?php
return array (
  334 => 
  array (
    'id' => '334',
    'catid' => '3',
    'typeid' => '0',
    'title' => '植发手术需要先进的植发技术做依托',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0203/20150203062539721.jpg',
    'keywords' => '先进 技术',
    'description' => '植发手术是一项新鲜事物，很多人以为，脱发的解决办法就是吃药、抹药&hellip;&hellip;如果脱发区毛囊组织已萎缩死亡，此时吃药、抹药等是没有任何作用的   ',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/zfjs/0203_334.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1422953437',
    'updatetime' => '1422959143',
  ),
  279 => 
  array (
    'id' => '279',
    'catid' => '3',
    'typeid' => '0',
    'title' => 'FUE-APL2.0无痕植发技术',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0203/20150203061423253.jpg',
    'keywords' => '技术',
    'description' => '植发手术是一项新鲜事物，很多人以为，脱发的解决办法就是吃药、抹药&hellip;&hellip;如果脱发区毛囊组织已萎缩死亡，此时吃药、抹药等是没有任何作用的   ',
    'posids' => '1',
    'url' => 'http://bjshenniao.zhifa.cc/zfjs/0120_279.html',
    'listorder' => '1',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421736351',
    'updatetime' => '1422958467',
  ),
  280 => 
  array (
    'id' => '280',
    'catid' => '3',
    'typeid' => '0',
    'title' => '国际先进无痕加密技术',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0203/20150203061407661.jpg',
    'keywords' => '先进 国际 技术',
    'description' => '雍禾植发LATTICE点阵加密技术是雍禾植发技术研究院数位国际知名植发专家，在植发技术第六次改革中，根据亚洲人皮肤、毛发特征，于2010年自   ',
    'posids' => '1',
    'url' => 'http://bjshenniao.zhifa.cc/zfjs/0120_280.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421737383',
    'updatetime' => '1422958452',
  ),
  281 => 
  array (
    'id' => '281',
    'catid' => '3',
    'typeid' => '0',
    'title' => 'UHE微米级无痕植眉技术',
    'style' => '',
    'thumb' => 'http://bjshenniao.zhifa.cc/uploadfile/2015/0203/20150203061323636.jpg',
    'keywords' => '微米 技术',
    'description' => '雍禾植发国际权威专家自主研发的UHE微米级无痕植眉技术是亚洲首个专门应用于眉毛种植的技术体系。采用国际植发界最先进APL2 0高密度、高精   ',
    'posids' => '1',
    'url' => 'http://bjshenniao.zhifa.cc/zfjs/0120_281.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1421737435',
    'updatetime' => '1422958407',
  ),
  329 => 
  array (
    'id' => '329',
    'catid' => '3',
    'typeid' => '0',
    'title' => '雍禾植发成功研发毛囊单位取发器',
    'style' => '',
    'thumb' => '',
    'keywords' => '毛囊 单位',
    'description' => '雍禾植发是业界关注的焦点，无论是国内首家毛囊实验室的成立、还是发布植发行业质量标准管理体系的出台，雍禾植发永远都是站在植发行业最前   ',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/zfjs/0203_329.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1422952735',
    'updatetime' => '1422957647',
  ),
  330 => 
  array (
    'id' => '330',
    'catid' => '3',
    'typeid' => '0',
    'title' => '植发技术有多少种，哪个好？',
    'style' => '',
    'thumb' => '',
    'keywords' => '技术',
    'description' => '当众多脱发患者经过生发药、中药调理、传统偏方等五花八门、琳琅满目的生发方法后，仍不能达到理想效果之时，最终敲开了植发的大门，可是大   ',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/zfjs/0203_330.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1422953213',
    'updatetime' => '1422957461',
  ),
  331 => 
  array (
    'id' => '331',
    'catid' => '3',
    'typeid' => '0',
    'title' => 'FUE-APL2.0无痕植发技术的效果调查',
    'style' => '',
    'thumb' => '',
    'keywords' => '效果 技术',
    'description' => '雍禾植发技术设备先进、专家一流、效果极佳，不管是消费者、同行、还是权威机构都对雍禾植发竖起大拇指，如果一个企业、一个组织机构要想成   ',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/zfjs/0203_331.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1422953291',
    'updatetime' => '1422957453',
  ),
  333 => 
  array (
    'id' => '333',
    'catid' => '3',
    'typeid' => '0',
    'title' => '​雍禾植发与其他植发机构技术上有何不同',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '雍禾植发作为植发行业领导者，植发技术与其他植发机构有何不同，雍禾在植发技术方面有哪些优势？雍禾植发技术领先体现在以下几点：　　1 取   ',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/zfjs/0203_333.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1422953386',
    'updatetime' => '1422953428',
  ),
  332 => 
  array (
    'id' => '332',
    'catid' => '3',
    'typeid' => '0',
    'title' => '无痕植发技术和有痕植发技术的区别',
    'style' => '',
    'thumb' => '',
    'keywords' => '技术',
    'description' => '头发种植是一种头部整形美容手术，这种头部整形手术主要运用自体毛囊种植技术进行头部的美容。很多人对于头发种植技术并不了解，有人说无痕   ',
    'posids' => '0',
    'url' => 'http://bjshenniao.zhifa.cc/zfjs/0203_332.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xuxiaobo',
    'inputtime' => '1422953346',
    'updatetime' => '1422953377',
  ),
);
?>