<?php
return array (
  39 => 
  array (
    'posid' => '39',
    'modelid' => '14',
    'catid' => '33',
    'name' => '首页新闻视频',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  38 => 
  array (
    'posid' => '38',
    'modelid' => '13',
    'catid' => '32',
    'name' => '首页美人尖种植案例',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  37 => 
  array (
    'posid' => '37',
    'modelid' => '13',
    'catid' => '31',
    'name' => '首页鬓角种植案例',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  36 => 
  array (
    'posid' => '36',
    'modelid' => '13',
    'catid' => '30',
    'name' => '首页睫毛种植案例',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  35 => 
  array (
    'posid' => '35',
    'modelid' => '13',
    'catid' => '29',
    'name' => '首页胡须种植案例',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  30 => 
  array (
    'posid' => '30',
    'modelid' => '1',
    'catid' => '3',
    'name' => '列表内页右侧推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  28 => 
  array (
    'posid' => '28',
    'modelid' => '1',
    'catid' => '33',
    'name' => '列表内页热点推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  27 => 
  array (
    'posid' => '27',
    'modelid' => '1',
    'catid' => '6',
    'name' => '列表雍禾新闻聚焦',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  26 => 
  array (
    'posid' => '26',
    'modelid' => '13',
    'catid' => '5',
    'name' => '列表内页雍禾案例',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  31 => 
  array (
    'posid' => '31',
    'modelid' => '13',
    'catid' => '25',
    'name' => '首页头发种植案例',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  22 => 
  array (
    'posid' => '22',
    'modelid' => '1',
    'catid' => '23',
    'name' => '首页雍禾成就',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  32 => 
  array (
    'posid' => '32',
    'modelid' => '13',
    'catid' => '26',
    'name' => '首页眉毛种植案例',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  33 => 
  array (
    'posid' => '33',
    'modelid' => '13',
    'catid' => '27',
    'name' => '首页发际线调整案例',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  34 => 
  array (
    'posid' => '34',
    'modelid' => '13',
    'catid' => '28',
    'name' => '首页疤痕种植案例',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  18 => 
  array (
    'posid' => '18',
    'modelid' => '1',
    'catid' => '0',
    'name' => '首页内容幻灯片',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  29 => 
  array (
    'posid' => '29',
    'modelid' => '1',
    'catid' => '0',
    'name' => '列表内页幻灯片',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  40 => 
  array (
    'posid' => '40',
    'modelid' => '14',
    'catid' => '60',
    'name' => '首页案例视频',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
);
?>